test/client.test.ts

1. Unsupported date format
2. cal:: module
3. Remove duration syntax that going to be disallowed
4. The `serializable` thing probably, something of the new postgres

Fix outdated tests, namely:

---

docs/api/types.rst
src/buffer.ts
src/codecs/datetime.ts
src/datatypes/datetime.ts
test/client.test.ts
test/types.test.ts

The controversial decisions:
1. `new Duration` takes **milliseconds** as it's what JS uses for `Date - Date`
2. Internally we store microseconds (but this can be changed in future)
3. Currently, it crashes with overflow when duration doesn't fit 53 bits (size of a float). But there are few ways to fix it (bigint in node > 12.0, split the number for earlier versions). But fortunately, it's forward-compatible.

Fix duration to obey new semantics

---

docs/api/connection.rst
docs/api/types.rst
test/client.test.ts

Add a cautionary note about fetching `decimal` values using
`fetchAllJSON` or `fetchOneJSON`.
State that `biging` is mapped onto `BigInt` in JavaScript.
Add some `fetchOneJSON` tests.
This is trying to address edgedb/edgedb#1151

docs: Add a note about using JSON when fetching values.

---

src/client.ts
tsconfig.json

The `@internal` annotation on methods forces TypeScript to hide
their existance from `.d.ts` files.
Fixes #15.

Hide private constructors with `@internal`

---

src/codecs/namedtuple.ts
test/client.test.ts

Fixes bug in `NamedTupleCodec.encodeArgs` where the properties of an args object are just assigned to the query args in the order that they are returned by `Object.keys`, not by name, leading to correctness bugs (if the types happen to be compatible) or codec encoding errors.
```js
const edgedb = require('edgedb') // 0.7.0-alpha.5
async function main() {
const conn = await edgedb.connect({
// connection config
})
try {
console.log(
await conn.fetchAll(`SELECT <int64>$a - <int64>$b`, {
a: 10,
b: 5,
})
)
// Set [ 5 ]
console.log(
await conn.fetchAll(`SELECT <int64>$a - <int64>$b`, {
b: 5,
a: 10,
})
)
// Set [ -5 ]
console.log(
await conn.fetchAll(`SELECT (
<int64>$number,
<str>$string
)`, {
string: 'test',
number: 42,
})
)
// Error: a number was expected, got "test"
// at Int64Codec.encode …
```

Fix bug when arg properties are in different order to query args

---

.github/workflows/tests.yml
src/client.ts
src/codecs/namedtuple.ts
src/codecs/tuple.ts

Ported from https://github.com/edgedb/edgedb-python/pull/89

Bring argument tuple encoding up to date with protocol version 0.8

---

src/client.ts
test/client.test.ts

Fixes bug where queries made after a query that fails with a no codec error, also fail as there is still the "T" message from the previous query left over in the read message buffer.
```js
const conn = await connect(...)
async function runQuery(query) {
try {
return await conn.fetchOne(query)
} catch (err) {
console.log(err)
}
}
console.log( await runQuery(`SELECT 123.456n`) )
// Error: no JS codec for std::decimal                 <-- Expected error
console.log( await runQuery(`SELECT 123.456`) )
// Error: unexpected message type 84 ("T")
//   at AwaitConnection._fallthrough (.../edgedb-js/dist/src/client.js:247:23)
//   at AwaitConnection._parse (.../edgedb-js/dist/src/client.js:426:26)
//   at AwaitConnection._fetch (.../edgedb-js/dist/src/client.js:637:58)
//   at …
```

Fix bug where connection is in broken state after no codec error

---

docs/api/connection.rst

Make the part of the class description talking about optional query
arguments more prominent and link to that section, rather than the
class.
Fixes #38

Update the API docs.

---

.gitignore
docs/api/connection.rst
docs/api/types.rst
docs/index.rst
docs/usage.rst
src/client.ts
src/index.node.ts
src/pool.ts
src/queues.ts
test/pool.test.ts
test/queues.test.ts
test/testbase.ts

The code mostly replicates the logic of the Python driver implementation.

Adds a connection pool

---

docs/api/connection.rst
docs/api/types.rst
docs/usage.rst
src/client.ts
src/ifaces.ts
src/index.node.ts
src/pool.ts
test/connection.test.ts
test/pool.test.ts
test/testbase.ts

First and foremost this commit drops the NodeJS-style callback APIs.
The callback-based 'connect()' still exists, although it now emits a
warning and isn't documented.
The motivation for dropping callback APIs is the excessive complexity
of the support code & overall UX they require.  While using callbacks is
what NodeJS started with, they are discouraged from being used in favor
of async/await.  And even if one needs to use callbacks, the
promise-based API makes that simple, just use '.then()' and '.catch()'
promise methods.
While at it, I refactored all APIs to be defined in terms of Connection
and Pool interfaces, which are now exported. All implementation details
are hidden from the user this way.  The PoolConnectionProxy now goes
even further, by using Symbols to make it impossible …

Drop callback-based Connection & Pool APIs

---

docs/api/connection.rst
docs/usage.rst
src/client.ts
src/con_utils.ts
src/credentials.ts
src/pool.ts
test/connection.test.ts
test/credentials.test.ts
test/credentials1.json
test/globalSetup.ts
test/pool.test.ts
test/testbase.ts

This adds positional argument to `connect()` and `createPool()` functions which can be either DSN or an instance name.
This is a part of what's discussed in https://github.com/edgedb/edgedb/discussions/1683 other things will follow in the next release.
This also deprecates `admin=True` parameter and `edgedbadmin` schema, as
they aren't needed if proper permissions are set up. And were introduced
mainly for command-line tools.
Supersedes #62

Implement named instances support

---

src/client.ts
src/index.node.ts

The class allows to use low-level "parse" and "execute" protocol messages
directly, using binary data.  This is a private API needed to EdgeDB
Studio.

Add new "RawConnection" class

---

test/pool.test.ts

Some tests are sporadically failing ([1130711574](https://github.com/edgedb/edgedb-js/runs/1130711574), [1032853292](https://github.com/edgedb/edgedb-js/runs/1032853292), [1114594457](https://github.com/edgedb/edgedb-js/runs/1114594457), [1060061425](https://github.com/edgedb/edgedb-js/runs/1060061425)) due to `pool.onAcquire` or `pool.onRelease` tests timing out. This increases the timeout from the default 5 seconds to 10 seconds.

Increase timeout for `pool.onAcquire` and `pool.onRelease` tests

---

src/client.ts
src/codecs/registry.ts
src/codecs/uuid.ts
src/con_utils.ts
test/client.test.ts
test/connection.test.ts

Due to JS' Map and Set objects hashing by identity (and not
via __eq__ and __hash__ like in Python), wrapping a UUID in
an object makes it way less usable.
From now on, by default, EdgeDB UUIDs will be decoded into JS
strings and decoded from JS strings. Since UUIDs are quite
common, they are decoded to strings as fast as possible. That
means that a '759637d8-6635-11e9-b9d4-098002d459d5' UUID would
be decoded into a '759637d8663511e9b9d4098002d459d5' string.
Although properly formatted UUIDs are accepted as input as well.
To enable the old behavior set the `legacyUUIDMode: true`
connect config option.
While at it, rename command_timeout and server_settings undocumented
connect config options to commandTimeout and serverSettings.

Switch UUID decoding from a rich object to a string

---

src/con_utils.ts

Fixes connecting to the local instances by an instance name (#71)

Don't use unix socket when using credentials

---

.github/workflows/tests.yml
src/client.ts

With how it's written before the change server returns the largest
protocol it supports and as long as server is updated JavaScript
bindings crash with unsupported protocol error.
This, together with edgedb/edgedb#2019 fixes tests with nightly edgedb.

Fixes forward compability with the new edgedb

---

src/client.ts
src/con_utils.ts
test/connection.test.ts

* Ignore extra headers by default
* Use `edgedb` as username and database name by default

Updates of the bindings to fix support of edgedb 1-beta1

---

src/compat.ts

> Safari crashes on my machine with "Error: JSBI library is required to polyfill BigInt"
https://github.com/edgedb/ui/pull/172#issuecomment-765772515
Fixes bug introduced in #68. A bigint constant was being assigned in the main body of the module, so in browsers without native BigInt the polyfill was being called when the module was loaded, and so before `plugJSBI` could be called to inject the BigInt polyfill.

Fix usage of bigint polyfill

---

src/client.ts
src/errors/base.ts
src/errors/index.ts
src/errors/map.ts
src/errors/tags.ts
src/ifaces.ts
src/legacy_transaction.ts
src/pool.ts
src/transaction.ts
test/legacy_transaction.test.ts
test/pool.test.ts
test/retry.test.ts
test/transaction.test.ts

Like in python PR edgedb/edgedb-python#146 this lacks documentations and also more robustness can be added later. But this provides correct future-proof API.

RFC1004: Add `try_transaction` and `retry`

---

src/codecs/ifaces.ts
src/codecs/registry.ts

Decodes the scalar type name annotation (https://www.edgedb.com/docs/internals/protocol/typedesc#scalar-type-name-annotation) into KNOWN_TYPES, so `ScalarCodec.getKnownTypeName()` returns the name of enum types.
https://github.com/edgedb/edgedb-js/blob/319857f06b651ea2dc047842ad968b2705990bdd/src/codecs/ifaces.ts#L88-L94
@1st1 `getKnownTypeName` returns the name for the `derivedFromTid` if it exists first. I'm not sure when derived types occur, so I'm not sure if this behaviour is correct? Shouldn't it check the typename of this type first, then for the derived type?

Decode scalar type names into codec

---

src/buffer.ts
src/client.ts
src/ifaces.ts
test/client.test.ts

Implicit typenames were removed by default in protocol version 0.9 (https://github.com/edgedb/edgedb/pull/2019). We need an api option to enable them (and implicit limits would be useful) for studio.
Todo:

Add option to implicitly fetch typenames

---

src/adapter.deno.ts
src/adapter.node.ts
src/con_utils.ts
src/credentials.ts

Details:
1. Uses current directory for project dir
2. Does not search of the ancestor directories (unlike CLI tool)
3. Now crashes if `edgedb.toml` not found and no parameters specified
Also includes implementation of `EDGEDB_INSTANCE` env var support

Implement reading project config

---

src/adapter.deno.ts
src/adapter.node.ts
src/con_utils.ts
src/credentials.ts
test/deno.test.ts
test/globalSetup.ts

While there, fix Deno (and our test suite) to connect to a TCP socket,
as Deno doesn't work well with Unix sockets on macOS.

Fix Deno to run without `--unstable`. Add a test that that's possible.

---

.github/workflows/deno-release.yml
.github/workflows/tests.yml
src/adapter.deno.ts
src/adapter.node.ts
src/client.ts
src/codecs/registry.ts
src/con_utils.ts
src/credentials.ts
src/globals.deno.ts
test/connection.test.ts
test/globalSetup.ts
test/globalTeardown.ts
test/testbase.ts
tools/compileForDeno.ts

Deno ALPN support is tracked at denoland/deno#11479

Add TLS support

---

docs/api/connection.rst
src/pool.ts

The client APIs are moving toward a pool first approach. This is the first step in that direction.

Deprecate access to single connections

---

src/adapter.deno.ts
src/client.ts

This required me some digging into nodejs source as 'sock.alpnProtocol'
was set to 'null' when checked on the "connect" event. Apparently we
need to use the "secureConnect" event when dealing with TLS sockets.
Fix that and add protocol validation.

Validate that the correct ALPN protocol was selected.

---

qb/playground.ts
qb/test/casts.test.ts
qb/test/for.test.ts
qb/test/literals.test.ts
qb/test/operators.test.ts
qb/test/select.test.ts
qb/test/setupTeardown.ts
qb/test/with.test.ts
src/reflection/typesystem.ts
src/syntax/select.ts
src/syntax/toEdgeQL.ts

Implement function tests for SELECT
Remove casting on strings, float64, and int64 when unnecessary
Fix toEdgeQL bugs relating to nested shapes

Functional tests

---

.github/workflows/tests.yml

Unpin node 16 from 16.8 in the github test workflow because a fix for https://github.com/nodejs/node/issues/40030 has been released.

Revert node 16 version pinning in CI

---

docs/api/connection.rst
src/index.node.ts
src/pool.ts
test/createClient.test.ts
test/globalSetup.ts
test/testbase.ts

Requiring users to call `createClient(undefined, {...})` to set
custom connection options seems cumbersome. Since this is a new
API we can simplify the signature.

Make createClient accept only one argument.

---

src/client.ts
test/connection.test.ts

This fixes a bug when clients don't detect broken connection when
inside a transaction.

Make connection socket state tracking more robust

---

src/client.ts
test/client.test.ts

Due to clients being opaque pools of connections it is no longer
possible to have session-level configuration controlled with EdgeQL.
Future edgedb-js versions will have a proper high-level API to define
session-level configuration.

Disable session config queries

---

src/conUtils.ts
test/connection.test.ts

- Add support for `tlsCA` and `credentials` options and env vars (https://github.com/edgedb/shared-client-testcases/pull/12)
- Add support for IPv6 addresses (https://github.com/edgedb/shared-client-testcases/pull/11)

Add support for `tlsCA` and `credentials` + support ipv6 addresses

---

src/credentials.ts

`tls_ca` replaces the deprecated `tls_cert_data` for consistency with
granular connection options.

Add support for `tls_ca` in `credentials.json`

---

src/client.ts

The `TransactionConflictError` class of errors is not only safe to
retry, it's _expected_ to be retried, so do that.

Retry mutating queries on transaction serialization errors

---

.github/workflows/deno-release.yml
.github/workflows/tests.yml
src/adapter.deno.ts
src/globals.deno.ts
test/client.test.ts
test/deno.test.ts
test/globalSetup.ts
test/globalTeardown.ts
test/testbase.ts
tools/compileForDeno.ts

Depends on https://github.com/edgedb/deno/commit/a95fef98b8c73894b985428e12f439c2730a5098

Implement ALPN support for the Deno adapter.

---

src/reflection/generators/generateCastMaps.ts

Currently there is a broken declaration for `getTsType` when generating for CJS via `--target cjs`, this PR should fix that.
```ts
declaretype getTsType<T extends $.BaseType> = T extends $.ScalarType
? T extends _std.$decimal | _std.$json | _std.$uuid
? never
: T["__tstype__"]
: never;
```

Fix getTsType generation on CJS

---

qb/dbschema/default.esdl
qb/dbschema/migrations/00003.edgeql
qb/test/insert.test.ts
qb/test/select.test.ts
src/reflection/builders.ts
src/reflection/generators/generateObjectTypes.ts
src/syntax/genMock/modules/std.ts
src/syntax/insert.ts
src/syntax/literal.ts
src/syntax/path.ts
src/syntax/toEdgeQL.ts

- Fix bug @colinhacks found during launch livestream where expressions get wrongly double counted when `select`ing a non basic path object and `select` contains nested shapes, causing expressions to be hoisted out of their parent scope.
- Fix bug in `toEdgeQL` causing this issue: #242 + fix cardinality/element type in other `insert unless conflict` cases
- Fix broken code gen when `default` module is empty (reported here: https://discord.com/channels/841451783728529451/849374705210490900/942414500567588954)

Various querybuilder fixes

---

src/reflection/generators/generateCastMaps.ts

Currently the declaration for `getSharedParentScalar` has a function body included, this PR should get rid of it in the declaration file.
```ts
declare function getSharedParentScalar<A extends $.ScalarType, B extends $.ScalarType>(a: A, b: B): A | B
as any
as any
```

Fix getSharedParentScalar declaration

---

qb/playground.ts
qb/test/insert.test.ts
qb/test/update.test.ts
src/syntax/casting.ts
src/syntax/insert.ts
src/syntax/update.ts

- Improve assignment expressions for `multi` properties
- Fix enum assignment expressions
Closes #260 and  #259 
Remaining issue: you can't pass `string[]` into `e.array()`. This is minor for now, we can merge without it since using `e.array` for literals is rarely necessary.

Support raw data for multi properties. Fix enum assignment expressions.

---

src/syntax/toEdgeQL.ts

Original PR: #273.
I accidentally got rid of the fork.
---
As found out by **tdolsen** and @jaclarke, the generated Typescript client does not play nicely with `noImplicitAny` set to `false`.
This PR should properly type the places where implicit anys exist.
This probably is also a Typescript bug, I would expect `noImplicitAny` set as `false` to do quite the opposite.
However I saw that the same variables were typed in other places of the code, so this change is probably justified.
Reproduction repository: https://gitlab.com/tdolsen/edgedb-testing/-/tree/de0ce6035350bd1dc8bc6bc7208da8e5a6acc8ac

Fix implicit any on toEdgeQL.ts (take #2)

---

qb/test/operators.test.ts
qb/test/params.test.ts
qb/test/select.test.ts
qb/test/sets.test.ts
qb/test/with.test.ts
src/syntax/toEdgeQL.ts

Instead of trying to determine if the child expr needs wrapping with `()` at every place where `renderEdgeQL` is used, make every expr wrap itself with `()` if it can't be safely used as a sub-expression without, and only unwrap at the top level.
Fixes #266

Refactor expr bracket wrapping in `toEdgeQL`

---

qb/package.json
qb/test/cardinality.test.ts
qb/test/collections.test.ts
qb/test/delete.test.ts
qb/test/detached.test.ts
qb/test/functions.test.ts
qb/test/insert.test.ts
qb/test/operators.test.ts
qb/test/testRunner.ts
qb/test/update.test.ts
qb/test/with.test.ts
qb/tsconfig.json
src/reflection/builders.ts
src/reflection/generators/generateCastMaps.ts
src/syntax/casting.ts
src/syntax/collections.ts
src/syntax/insert.ts
src/syntax/literal.ts
src/syntax/path.ts
src/syntax/query.ts
src/syntax/select.ts
src/syntax/set.ts
src/syntax/syntax.ts
src/syntax/with.ts

Fixes #268
It seems Sveltekit cannot identify imports that only import types without the explicit `import type` syntax, and so imports of the stdlib types from `modules/std` in castmaps, etc. cause the circular import problem (Previously seen here: https://github.com/edgedb/edgedb-js/commit/a8e32965c0d4fc93ef22d1d962ce1da492abd262 and https://github.com/edgedb/edgedb-js/pull/225/commits/96039d1e4bf12638ed002d12100b3fbfa65fe746).

Update codegen and /syntax to use `import type` where only the type import is needed

---

.github/workflows/release.yml

This changes the CI to publish to NPM whenever the `package.json` is modified in `master`. This is more conventional than running release CI for PRs that aren't yet merged. 
For the moment `npm publish` is executed with the `--dry-run` flag for testing purposes.

Run publish on push to master

---

src/reflection/generators/generateSetImpl.ts

The code generation for **CJS** and **ESM** generates invalid syntax for declaration files.
// dbschema/edgeql-js/syntax/setImpl.d.ts
```
declare function set<Expr extends TypeSet<BaseType> | castMaps.scalarLiterals>(
...exprs: Expr[]
): $expr_Set<
TypeSet<
getPrimitiveBaseType<castMaps.literalToTypeSet<Expr>["__element__"]>,
Cardinality.Many
>
>;
)
.reduce(getSharedParent),
__cardinality__: cardinalityUtil.mergeCardinalitiesVariadic(
exprs.map(expr => expr.__cardinality__)
),
__exprs__: exprs,
});
}
```
This PR should fix the function body ending up in the declaration file.

Fix set impl function body ending up in declaration files

---

package.json
src/baseConn.ts
src/client.ts
src/codecs/ifaces.ts
src/codecs/namedtuple.ts
src/codecs/object.ts
src/fetchConn.ts
src/rawConn.ts
test/client.test.ts
yarn.lock

Requires the server to run with https://github.com/edgedb/edgedb/pull/3682.
------
@jaclarke James, I hope this would unblock you to implement querying from the admin panel.
Some notes:
1. I've only tested this running from the nodejs environment (not browser). The key limitation here is that node (pre 17.5) doesn't have native `fetch()`, so I'm using `node-fetch` to emulate it for testing purposes. When you run this in the browser, you might need to update `FetchSocket.write()` to properly cast emulated `Buffer` to something that browser's `fetch()` can understand (most likely `ArrayBuffer`).
2. Every HTTP request essentially creates a new (temporary) binary connection on the server. Which means that the typical `[parse] [execute]` message sequence doesn't work! 
* When you execute …

Binary protocol channeling over HTTP

---

docs/index.rst

I was reading the docs and I wanted to fix
```ts
const q1 = await e.str("Hello world!").run(client);
// number
```
since the inferred type is actually the string literal `"Hello world!"`. But I thought that writing `"Hello world!"` instead of `number` seems confusing. So I thought that maybe using an addition so that the inferred type is `string` is a better idea.
Also I've added `run()` at the end of the code since I was expecting the code to run something by itself without me having to write `run()` afterwards. But this is debatable so I can undone the change.

Improve the docs and fix number to string

---

package.json
src/codecs/datetime.ts
src/codecs/numbers.ts
src/codecs/numerics.ts
src/codecs/registry.ts
src/compat.ts
src/datatypes/datetime.ts
src/primitives/bigint.ts
test/client.test.ts
test/types.test.ts
yarn.lock

- Update to latest temporal polyfill for tests
- Add `from` method to `Duration` type according to temporal spec: https://tc39.es/proposal-temporal/#sec-temporal.duration.from
- Re-organise custom codecs:
- drop `bigint` -> `string` codec: not needed since bigint's are supported pretty much everywhere and we can polyfill when they aren't
- change `int64` -> `string` to `int64` -> `bigint`: so we can add encode codec
- drop `local_datetime` codec and change `datetime` codec to decode into a `LocalDatetime`: datetime types now fit into `Date` type (https://github.com/edgedb/edgedb/pull/2252), except `datetime` needs `local_datetime` codec because `Date` doesn't have microsecond precision
- Add encode codec for decimal strings

Custom codecs update

---

qb/dbschema/default.esdl
qb/dbschema/migrations/00012.edgeql
qb/test/insert.test.ts
qb/test/objectTypes.test.ts
qb/test/update.test.ts
src/reflection/generators/generateObjectTypes.ts
src/syntax/insert.ts
src/syntax/toEdgeQL.ts

- Fix generated edgeql for empty insert/update shapes + throw runtime error if insert shape is not object (Closes #306)
- Fix handling of overloaded properties (Fixes #315)

Fix qb bugs

---

.github/workflows/tests.yml
qb/playground.ts
qb/test/params.test.ts
src/codecs/uuid.ts
test/client.test.ts
test/session.test.ts

Did some simple benchmarking on UUID parsing, see `qb/playground.ts` to see the various implementation.
I landed on an implementation from https://github.com/uuidjs/uuid/blob/main/src/stringify.js that's actually 22% faster than what we have currently and adds hyphens properly.
```
without-dashes: 821.39ms // current
with-dashes-bytetohex: 634.192ms // new
with-dashes-readbuffer: 1.714s
with-dashes-string-manip: 841.354ms
with-dashes-string-addition: 875.214ms
```

Use byteToHex to decode uuid

---

.github/workflows/tests.yml

Skips running tests for `README.md` and anything under `docs/`.
[This has a side-effect of not passing PR status checks due to the workflow being added and then skipped due to the path filter](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks).
P.S. Now that I pull requested, should we also ignore `.github/` (or stricter like `.github/ISSUE_TEMPLATE/`)?

Skip tests for README/docs

---

qb/test/group.test.ts
src/syntax/toEdgeQL.ts

Reported on discord: https://discord.com/channels/841451783728529451/1022077368984150016

Fix `e.group` codegen when grouping a nested `e.select`

---

docs/querybuilder.rst

A user created a repo comparing a task model implementation in Knex and EdgeDB. User was under the impression it was not possible to use the querybuilder with transactions. This is part of an effort to better communicate that it is possible.
See https://discord.com/channels/841451783728529451/1038780233458909324/1039094288354652180
Companion to https://github.com/edgedb/edgedb/pull/4640

Add an example for using the query builder in a transaction

---

packages/driver/src/ifaces.ts

To support the fact that `json` can now be `unknown`. Closes #469

Relax QueryArg type

---

docs/select.rst
packages/generate/src/syntax/select.ts
packages/generate/test/select.test.ts

Polymorphic queries such as this are currently broken:
```
e.select(e.Content, () => ({
...e.is(e.Movie, e.Movie['*'])
}))
```
This PR fixes these queries by allowing fields that exists on the parent type to contain polymorphic element expressions. `e.is` now also filters out `id` fields in the shape object, since these are invalid in EdgeQL, and this seems more convenient than forcing users to filter it out themselves (especially when using `['*']`). This shouldn't be a breaking change, as these queries previously didn't generate valid edgeql, so would have always failed at runtime anyway.

Fix all properties shorthand (`['*']`) inside polymorphic queries

---

packages/generate/src/queries.ts

fixes #499 
A naive attempt to fix typing issue in generated query.
Both Transaction and Client conforms to Executor interface, so Executor should be used as the type for client in generated query function.
The same way it's done in query builder.
I didn't test the code.

🏷️ use Executor type for client in generated query

---

packages/generate/src/syntax/typesystem.ts

Hopefully should fix #502 and #493

Fix 'union type that is too complex to represent' error under typescript 4.9

---

packages/generate/src/syntax/select.ts

Fix bug to allow params to be used as `limit` in select

---

packages/generate/src/syntax/params.ts
packages/generate/src/syntax/query.ts
packages/generate/test/params.test.ts

Fixes issue reported on Discord: https://discord.com/channels/841451783728529451/1054101776665686166/1054517955523784765

Fix codegen when expression wrapped by `e.params` is non-runnable

---

packages/driver/src/fetchConn.ts

Fetch-based connection classes:
* never set `connWaiter` event, which is inherited from `BaseRawConnection`;
* set, but don't clear `messageWaiter` after receiving data.
This results in a "client has been closed" error when calling `Client.close()` on an HTTP client.
This PR fixes the issue above.

Fix event handling in fetch-based connection classes

---

packages/driver/src/fetchConn.ts
packages/driver/test/client.test.ts

This PR adds support for HTTPS connections in `FetchConnection` and `AdminUIFetchConnection`. An HTTP connection is established if `tlsSecurity` is set to `insecure`; otherwise, the connection will be made over HTTPS.

Support HTTPS connections in HTTP client

---

docs/insert.rst
packages/generate/src/syntax/insert.ts
packages/generate/test/insert.test.ts

Though not valid in edgeql, it seems reasonable to allow a named tuple to be passed as the shape of an insert expression for convenience in the querybuilder, instead of requiring the user to manually re-define the object.
Fixes #523

Allow a named tuple to be passed as the shape of an insert

---

packages/generate/src/syntax/path.ts
packages/generate/src/syntax/select.ts
packages/generate/src/syntax/update.ts
packages/generate/test/select.test.ts
packages/generate/test/update.test.ts

Fixes #548
When using `filter_single` we always assume the result to have singleton cardinality. However when used with an arbitrary expr instead of the object api, we cannot guarantee that edgedb will infer singleton cardinality for the result, so in this case the querybuilder should inject `assert_single` to ensure inferred cardinality stays in sync.

Inject `assert_single` when using `filter_single` not with exclusive object api

---

packages/generate/src/syntax/collections.ts
packages/generate/src/syntax/external.ts
packages/generate/test/collections.test.ts

Fixes #541
Adds a function that takes an object type expression, and converts it to a tuple type containing by default the non-computed properties (excluding 'id'). Eg:
```ts
import e, {objectTypeToTupleType} from "./dbschema/edgeql-js";
const movieTuple = objectTypeToTupleType(e.Movie);
// => tuple<genre: default::Genre, rating: std::float64, title: std::str, release_year: default::year>
```
Specific fields can by selected be providing a second arg:
```ts
const movieTuple2 = objectTypeToTupleType(e.Movie, ['title', 'rating']);
// => tuple<title: std::str, rating: std::float64>
```

Add helper function to create tuple types from object types

---

packages/generate/package.json
packages/generate/src/syntax/path.ts
packages/generate/test/objectTypes.test.ts

Fixes this bug reported on discord: https://discord.com/channels/841451783728529451/849374705210490900/1081691035199090708

Fix `['*']` on scoped object of `e.select` on an `insert` expr

---

.github/workflows/tests.yml

Since nightly is a fast moving, and unstable target, I don't think it makes sense to fail all of the other test runs in the matrix if the nightly tests fail. Still worth knowing if it succeeds or not, but I think it makes the most sense to still run the other tests against stable.

Do not cancel other tests if nightly fails

---

.github/workflows/release.yml

We accidentally broke this in https://github.com/edgedb/edgedb-js/commit/8cc171faabfe650a05a226f02a0e961a44c67aec when we removed the bit of configuration for getting the `fromTag`. Took a second to realize this was happening but looking in the last version that would've run this, I saw this:
And since, by default, it doesn't output uncategorized PRs, it was blank.

Update changelog config to valid JSON

---

packages/generate/src/syntax/toEdgeQL.ts
packages/generate/test/for.test.ts
packages/generate/test/with.test.ts

In some cases when an expression is re-used inside a `for` expr, the `with` var it gets automatically extracted into gets bound to the outside of the `for` expr, which if the `with` expr references the loop var it causes an error. See: https://discord.com/channels/841451783728529451/849377751370432573/1098317767289090149
This PR fixes how the common parent scope of all usages of an expr is computed, so the `with` vars are correctly bound to the `insert` expr in this example. Also fixes a bug where child exprs in the `unless conflict` clause of an `insert` were not being correctly tracked as children of the `insert` expr.

Fix with var extraction in `for` loops + fix `insert unless conflict` child expr tracking + add tests

---

packages/driver/src/primitives/buffer.ts
packages/driver/src/rawConn.ts

Should fix #571.
Currently if the ring buffer that incoming data is placed into overflows, an error is thrown for the currently running query but the ring buffer is never cleaned up, so subsequent queries will also fail.
For now the safest fix seems to be to just abort the connection if the ring buffer overflows, since cleaning up the buffer properly will probably require some refactoring to track the boundaries of the separate messages in the buffer.
Also bump the ring buffer size by 4x, to allow larger results, though this also is a temporary fix, and we should probably find a way to remove this query result size limitation.

Bump ring buffer size + abort conn if ring buffer overflows

---

packages/driver/test/testUtil.ts

Turns out this was all it took to properly link to `"/User/someone/Library/Application Support/edgedb/portable/bin/edgedb-server"`, which is the default path for macOS. We're already using `spawn` downstream which correctly handles paths with spaces.

Use `spawnSync` to allow spaces in server bin path

---

.git-blame-ignore-revs

Ignore the changes made in #580 when using `git blame` and other tools that honor the `.git-blame-ignore-revs` file like GitHub https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

Ignore prettier config change by commit hash

---

packages/driver/src/adapter.deno.ts
packages/driver/src/rawConn.ts

Remote might rely on SNI to route the connection request properly, so
make sure to send it.

Fix TLS SNI

---

.github/workflows/tests.yml
packages/driver/package.json
packages/driver/src/httpScram.ts
packages/driver/test/browser.test.ts
packages/driver/test/createClient.test.ts
packages/driver/test/jsdom-with-fetch.ts

Node v14 is end-of-life at the end of the month, and Node v20 is out, so this moves our testing matrix window forward based on the current LTS schedule. I picked v18 as our common version to test against in the extra versions since v16 is technically in maintenance mode and will be EOL in 6 months.
As of today:
Source: https://github.com/nodejs/Release
<details>
<summary>Release schedule JSON</summary>
```json
{
"v0.8": {
"start": "2012-06-25",
"end": "2014-07-31"
},
"v0.10": {
"start": "2013-03-11",
"end": "2016-10-31"
},
"v0.12": {
"start": "2015-02-06",
"end": "2016-12-31"
},
"v4": {
"start": "2015-09-08",
"lts": "2015-10-12",
"maintenance": "2017-04-01",
"end": "2018-04-30",
"codename": "Argon"
},
"v5": {
"start": "2015-10-29",
"maintenance": "2016-04-30",
"end": "2016-06-30"
},
"v6": …
```

Update node version matrix for current LTS

---

packages/driver/src/codecs/numerics.ts
packages/generate/dbschema/default.esdl
packages/generate/dbschema/migrations/00020.edgeql
packages/generate/dbschema/queries/get-movies-starring.edgeql
packages/generate/test/interfaces.test.ts
packages/generate/test/objectTypes.test.ts
packages/generate/test/queries.test.ts
packages/generate/test/select.test.ts

Closes #602 
We set up the `ScalarCodec` with `unknown` as the `tsType` and override it when extending `ScalarCodec`. We were not doing it in this case.

Add decimal property to Person and test query

---

docs/querybuilder.rst

I notice we already have an example of this in "Globals" just above, but it could be easy to miss if you're not interested in referencing globals in particular. I wanted to draw attention to a couple of examples of how to reference entities on non-`default` modules with the query builder. (Recycled the one in "Globals," but I think it's useful to call attention to it again here.)

Add examples of referencing non-default modules

---

packages/generate/package.json
packages/generate/test/cardinality.test.ts
packages/generate/test/casts.test.ts
packages/generate/test/cli.test.ts
packages/generate/test/collections.test.ts
packages/generate/test/delete.test.ts
packages/generate/test/detached.test.ts
packages/generate/test/for.test.ts
packages/generate/test/functions.test.ts
packages/generate/test/globals.test.ts
packages/generate/test/group.test.ts
packages/generate/test/insert.test.ts
packages/generate/test/interfaces.test.ts
packages/generate/test/json.test.ts
packages/generate/test/literals.test.ts
packages/generate/test/objectTypes.test.ts
packages/generate/test/operators.test.ts
packages/generate/test/params.test.ts
packages/generate/test/paths.test.ts
packages/generate/test/primitives.test.ts
packages/generate/test/queries.test.ts
packages/generate/test/select.test.ts
packages/generate/test/sets.test.ts
packages/generate/test/update.test.ts
packages/generate/test/with.test.ts
yarn.lock

Wrote a [quick-and-dirty jscodeshift code mod](https://github.com/scotttrinh/expect-to-assert) to do this automatically, but there were a few manual interventions I had to do. I will outline those inline.
1. BETTER TYPES! Most of the `assert` functions are actual TypeScript assertion functions, so we can eliminate a bunch of `!` and `?` and `as any` calls littered around the test code. I, for one, would rather have the tests have the tightest possible types since we're relying on the tests as automated checks.
1. I find it way easier to read and understand:
```ts
assert.equal(a, b, "a is b");
```
than
```ts
// A is b
expect(a).toBe(b);
```
2. The new assert diffs are fire, and having the message in the failing tests is a great quality of life improvement.
New assert diff with message: …

Use `node:assert/strict` instead of Jasmine `expect` in generator tests

---

docs/queries.rst
packages/generate/src/queries.ts

Closes #540 #568 
Apparently this has never worked since importing `getUser.edgeql` would attempt to import the original query file rather than `getUser.edgeql.ts`, and TypeScript doesn't support specifying an extension for a TypeScript module unless you enable [`allowImportingTsExtensions`](https://www.typescriptlang.org/tsconfig#allowImportingTsExtensions) but then the emitted file has the wrong extension, so you would need to do some rewriting at buildtime to convert `ts` -> `js` for most build systems.

Avoid import collision for queries generator

---

packages/generate/src/queries.ts
packages/generate/test/queries.test.ts

Closes #470 
Export types we generate for the parameters to the query and the return type of running the query.
**Note**: I chose to _not_ return a type for `FooArgs` if the query does not take parameters rather than exporting `never`. I initially thought it would be good to have some symmetry and consistency here, but I decided to leave it out for now since adding it later is a backward compatible change, but removing it would be a breaking change.

Add Args and Returns types to queries generator

---

.github/workflows/tests.yml
packages/generate/test/globals.test.ts
packages/generate/test/group.test.ts
packages/generate/test/insert.test.ts
packages/generate/test/literals.test.ts
packages/generate/test/params.test.ts

Closes #612 
Add a check for 2.x to the testing matrix for when 3.x becomes stable soon.
I wanted to be able to query the EdgeDB instance that the `generate` package uses from CI. However, the migrations in that project are not valid for the 1.x server. I discussed with the team and we're fine with dropping 1.4 from the testing matrix. That's not an indication that the driver doesn't work with 1.x, but we're no longer checking for compatibility going forward.

Add explicit CI check for 2.x

---

packages/driver/src/conUtils.ts

Nebula switched to doing this, and so the clients must follow.

Lowercase org/instance name when computing Cloud instance DNS

---

packages/driver/src/codecs/datetime.ts
packages/driver/test/datetime.test.ts

Fix `LocalDateTimeCodec` decode for datetimes before postgres zero epoch

---

docs/querybuilder.rst
packages/generate/test/delete.test.ts

I was pairing with @DijanaPavlovic on doing this exact thing, and it took us both a few minutes to wrap our heads around this so thought it was worth adding an example to the docs.
Added a test to make sure I didn't screw this up!

Add example: filtered delete with `in` operator

---

packages/generate/src/queries.ts

Simple fix for #672. I'm slightly worried about the newline literal causing some weird pitfall with windows somehow.

Added linting rule for deno

---

integration-tests/stable/pgvector.test.ts
integration-tests/stable/setupTeardown.ts
packages/driver/src/reflection/queries/types.ts
packages/generate/src/syntax/funcops.ts

Closes #685 
The type system resolves ancestor types to scalars calling them "material scalars" and we were not getting any `ext::*` scalars in our subquery that resolves these.
Some additional updates to make error messages a bit more useful since they currently print `[object Object]` instead of anything useful 😬

Add any existing `ext::*` scalar to a type's `__casttype__`

---

.github/workflows/tests.yml
integration-tests/lts/dbschema/default.esdl
integration-tests/lts/dbschema/migrations/00021.edgeql
integration-tests/lts/interfaces.test.ts
integration-tests/lts/objectTypes.test.ts
integration-tests/lts/params.test.ts
packages/generate/src/edgeql-js/generateObjectTypes.ts

We do not need to generate a separate object type for a type that is a union of other types since we will have already generated the individual types and the use of that type within another type will be handled by the declaration of the consumer of the union.
TODO:
- You cannot make an alias union type. There are ways for an alias to have a type that is a union (making it a computed set of each type), but the reflection query is likely the same, so I'll consider this fine for now.

Handle >2 union members in links

---

packages/generate/src/cli.ts
packages/generate/src/edgeql-js.ts
packages/generate/src/queries.ts

Currently I have `watch: true` only to prevent the function from calling exit. Very weird lol.
It appears this functionality is stubbed, so dropping this seems fine. Even when implemented I'd question if this would be needed.

 Remove/move exit calls from generators to cli.ts

---

packages/generate/src/edgeql-js.ts

I run this command in docker build to generate the files.
It's not the first run; I've already configured my repo.
Also, for some reason this logic causes the docker build to exit early instead of finishing the generation.
I didn't look too closely into that, because I never want this logic to run.

Respect an explicit false for updateIgnoreFile

---

packages/generate/src/queries.ts

Closes #678 
**Note**: There is an existing bug here: we should be looking up your dbschema directory from your edgedb.toml configuration instead of hardcoding this, but I'll fix that in the context of #617 and a general `include`/`exclude` solution.

Ignore the dbschema/fixups directory in queries generator

---

packages/generate/src/syntax/collections.ts
packages/generate/src/syntax/insert.ts
packages/generate/src/syntax/path.ts
packages/generate/src/syntax/range.ts
packages/generate/src/syntax/select.ts
packages/generate/src/syntax/set.ts
packages/generate/src/syntax/toEdgeQL.ts
packages/generate/src/syntax/update.ts

Trying to use the query builder together in a SvelteKit project throws some errors.
The fix is to just do what the compiler suggested. 
Found another user hit with the bug on the main repo: https://github.com/edgedb/edgedb/issues/5486

Fix typescript errors for generated query builder

---

packages/driver/src/errors/base.ts
packages/driver/test/errors.test.ts

Closes #730 
In the case where an error message does not include source location, we should _still_ show any details or hints that the error does include.

Show details and hints in error message

---

.eslintrc.cjs
integration-tests/nightly/auth.test.ts
integration-tests/nightly/dbschema/default.esdl
integration-tests/nightly/dbschema/migrations/00002.edgeql
packages/generate/src/edgeql-js/generateGlobals.ts

Found a place where we were not properly escaping nested module names: globals. The name is not important here because it's not actually exported, it's added as a key on the module at `global`.

Properly escape nested module names for globals

---

.github/workflows/release.yml

Update the release GitHub action to trigger publishing the new auth packages to npm and also create the relevant changelogs.
I also did a bit of restructuring of the changelogs to be inline with the associated package instead of clumped at the end. Hopefully there aren't any runtime issues with moving the env vars to the beginning, but I couldn't think of how it might be affected.

Add new auth packages to release GitHub action

---

.github/workflows/release.yml

The release was failing due to the order of the build: It was building `@edgedb/auth-core` first which meant it didn't have access to `edgedb` types.
I moved this to just specifying the build as part of each package's section.

Build each package in order

---

.github/workflows/release.yml
.github/workflows/tests.yml
integration-tests/legacy/package.json
integration-tests/lts/package.json
integration-tests/nightly/package.json
integration-tests/stable/package.json
package.json
packages/auth-core/package.json
packages/auth-nextjs/package.json
packages/driver/package.json
packages/driver/src/baseConn.ts
packages/generate/package.json
yarn.lock

This fixes an issue in v1 where the action was overriding the `.npmrc` file which was causing subsequent calls to `npm` or `yarn` to have a malformed `.npmrc`. This was fixed in v2. We are pinning the action to version v3.0.1 which is the latest version as of today.
The other notable change here:
> The `type` output is now an empty string instead of 'none' when no release occurs
https://github.com/JS-DevTools/npm-publish/tree/v3.0.1#v2-output-changes

Use latest npm-publish action

---

packages/auth-nextjs/src/app/index.ts
packages/auth-nextjs/src/shared.ts

When requesting the reset password email, the URL from config is used, but was not really set during `auth` initialization.
The `resetUrl` param is not supported, so I've removed it from the type.

Use the configured passwordResetUrl in `auth-nextjs`

---

packages/auth-core/src/core.ts
packages/auth-core/src/crypto.ts
packages/auth-core/src/pkce.ts
packages/auth-core/test/crypto.test.ts
packages/auth-nextjs/src/app/index.ts

Closes #779 
I considered doing something dynamic to use `node:crypto` if run in the Node environment but that had two drawbacks: complexity, and making it harder to test. Since this path is not a hot-path, it doesn't seem like a good candidate for the tradeoff of complexity and performance that having a dynamic dispatch would provide.

Use Web-compatible crypto for PKCE

---

packages/auth-core/src/core.ts
packages/auth-nextjs/src/app/index.ts

Extracted from #778 while we figure out how we want to do integration testing.

Fix missing verifier from password reset flow

---

packages/auth-core/src/core.ts
packages/auth-nextjs/src/app/index.ts
packages/auth-nextjs/src/shared.ts

Depends on https://github.com/edgedb/edgedb/pull/6469

Multiple fixes/improvements to auth-nextjs

---

packages/driver/src/codecs/datetime.ts
packages/driver/src/datatypes/datetime.ts
packages/driver/test/types.test.ts

This is essentially just removing/"hiding" private fields, so that TS doesn't try to use those fields when checking type compatibility.
Previously, this failed type check, and now it doesn't
```ts
const ld: edgedb.LocalDate = Temporal.PlainDate.from('2023-11-27');
```
There are `instanceof` checks on our temporal classes in some places, so this isn't a complete solution but it does help ease TS friction.

Update temporal shapes to be compatible with Temporal API instances

---

packages/driver/src/adapter.deno.ts
packages/driver/src/primitives/buffer.ts

Closes #674
Avoid copying an existing buffer when encoding buffer data as base64. Also prioritizes using `Buffer` instead of `btoa` if both exist.

Avoid copying existing buffer in base64 encoder

---

docs/querybuilder.rst

Index `toEdgeQL` for doc search

---

integration-tests/lts/operators.test.ts
packages/driver/src/reflection/queries/operators.ts
packages/generate/src/edgeql-js/generateOperatorTypes.ts
packages/generate/src/syntax/funcops.ts

We still map this to the old style in the generated EdgeQL for now. Since the reflection doesn't give us separate operator definitions, we don't have an easy way to reflect which form is available to you.
We can make this distinction in the future by providing an optional `__form__` expression property and generating the appropriate EdgeQL based on that, but for now since we don't have an easy way to tell ifthe EdgeDB server supports it without hardcoding some notion of that into the generated logic, seems best to not do this yet.
Closes #794

Support new functional `if..then..else` syntax

---

.github/workflows/release.yml

I should've just added this to #805 🙈

Add publish step for `@edgedb/auth-express`

---

packages/generate/src/queries.ts

Functions are currently generated using the async keyword, despite not running async. They return a promise directly. This change slightly reduces the size of generated code and stops linters from yelling about unneeded async.

Removed unneeded async keyword

---

packages/auth-express/package.json
packages/auth-express/tsconfig.json

Noticed that TypeScript was complaining about missing types, so did a [little bit of research](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-exports) on how declaration files are found during module resolution and came up with this minimal addition which fixes the issue locally in the example app I'm working on.

Update `@edgedb/auth-express` module spec

---

docs/funcops.rst
docs/parameters.rst
docs/update.rst
integration-tests/lts/update.test.ts

This came up in the context of a user who was trying to figure out how to optionally update a property of an object with the query builder.
Noticed that our sole test case wasn't even really testing this either 🤦

Update docs and tests for optional parameters on update

---

packages/create/src/recipes/_edgedb/index.ts
packages/create/src/recipes/_edgedb/template/dbschema/default.esdl
packages/create/src/recipes/_edgedb/template/edgedb.toml
packages/create/src/recipes/_install/index.ts
packages/create/src/recipes/index.ts
packages/create/src/utils.ts

Includes a step that will attempt to install the CLI. Only works for *nix like systems at the moment due to how we have to spawn the commands in a "login shell" to get the correct PATH to include the `edgedb` CLI. The workaround for Windows users at the moment will be to install the CLI following the Windows installation instructions from the website before using the create-app flow.
Going to keep this as a draft to allow the base branch to land in `master` so this can land as a separate commit into `master` as well, but it should be ready for review.

Add EdgeDB create-app recipe

---

.github/workflows/tests.yml
packages/create/package.json
packages/create/src/recipes/_edgedb/index.ts

This drifted between my PR and the base. Added a simple `tsc --noEmit` check for this package to avoid hitting this simple case of a type error slipping through CI.

Call `copyTemplateFiles` with correct arguments

---

.github/workflows/tests.yml
integration-tests/lts/bench.ts
integration-tests/lts/package.json
yarn.lock

🎩 to @tbezman in #828 for pointing the way here.
Hoping that these type instantiations can be a good proxy for general performance of LSP.
Some things I'd like to add to this in future PRs:
- More benches
- Use the builtin functionality for testing multiple typescript versions
- Charting the changes over time

Establish baseline for select type instantiations

---

integration-tests/lts/bench.ts
packages/generate/src/syntax/select.ts

Thanks to the quick feedback cycle introduced by #829 was able to spend some time speeding up the `select` types. Was able to determine that the `scope` variable was the part of the expression that was taking the most time, and moved the type instantiation to a generic.

Move expensive type expressions to generic

---

integration-tests/lts/bench.ts
packages/generate/src/syntax/typesystem.ts

While investigating compatibility with the latest version of TypeScript (5.3.3 at the moment), I was working against the `main` branch of TypeScript and found a case where `e.literal` was causing a `TS2589: Type instantiation is excessively deep and possibly infinite.` error.
There are additional issues on 5.3.3, but this was one that was detectable and fixable in isolation, so adding this fix now. Might be a fix for #782 but I haven't been able to repro that issue.
Not sure why there is a benchmark regression here. I'm also getting this against `master`, so maybe there are some weird environmental issues that affect the benchmarks and make them slightly non-deterministic? 🤷

Remove extra flattening of array literal

---

integration-tests/lts/bench.ts
packages/driver/src/reflection/typeutil.ts
packages/generate/src/syntax/params.ts
packages/generate/src/syntax/select.ts
packages/generate/src/syntax/typesystem.ts

A handful of smaller improvements. Some of these are micro-optimizations, but a few had some measurable impact. I don't think there is much low-hanging fruit that I can use these same tricks on as far as I can tell, but here are the general flavors of these changes:
- Preferring `Omit` + intersection to "replace" a particular property on a type instead of mapping each property directly.
- Name unions used in conditional types
- Name internal conditional types within a larger conditional type
None of these seem to be silver bullets, and required actually benchmarking the changes to detect if they made things worse or better. Still not sure if I have a good intuition yet.

Some continued performance improvements

---

packages/generate/src/edgeql-js/generateInterfaces.ts
packages/generate/src/edgeql-js/generateScalars.ts
packages/generate/src/genutil.ts

As far as I've been able to deduce there's no need to jump to the `type`'s first `base` type to determine the TS literal value.
This is because the function already jumps to the `type`'s `material_id`, which has already worked out the "base concrete type".
https://github.com/edgedb/edgedb-js/blob/dfcf3d48f74fd78c47146b505a4e942d4b33d849/packages/driver/src/reflection/queries/types.ts#L165-L169
https://github.com/edgedb/edgedb-js/blob/dfcf3d48f74fd78c47146b505a4e942d4b33d849/packages/driver/src/reflection/queries/types.ts#L139-L144
This change resulted in no changes in my generated query builder, schema, or query files, so I'm fairly confident in it. Though not 100% and I don't know the difference between `bases` and `ancestors` (maybe they are the same for `ScalarType`?).
---
With that …

Allow scalarToLiteralMapping to declare TS type for extended scalar type

---

docs/update.rst

Add an example of `select(update())` to the docs

---

packages/auth-sveltekit/src/server.ts

We only use Partial<AuthRouteHandlers> so it's better to make properties optional right away.

Fix types in auth-sveltekit

---

integration-tests/lts/select.test.ts
packages/generate/src/syntax/select.ts

Closes #621 
Build a `TypeSet` in a similar way to `e.select` and use the existing `$infer` utility type.

Allow `$infer` to work on `e.shape` objects

---

integration-tests/lts/insert.test.ts
integration-tests/lts/params.test.ts
packages/generate/src/syntax/casting.ts
packages/generate/src/syntax/typesystem.ts

This is safe because it's saying we expect less.
Rather than giving less on output, which could be a breaking change.

Accept readonly arrays on assignment

---

packages/driver/src/baseConn.ts
packages/driver/src/reflection/analyzeQuery.ts
packages/driver/src/reflection/index.ts

I'm trying to get immutable output types, without duplicating a bunch of this code.

Break down analyzeQuery for more generation flexibility

---

integration-tests/lts/dbschema/queries/get_movies_starring.edgeql
integration-tests/lts/queries.test.ts
packages/driver/src/reflection/analyzeQuery.ts

Same as #884, but for query files instead of the query builder

Accept readonly arrays on generated query file args

---

integration-tests/lts/dbschema/default.esdl
integration-tests/lts/dbschema/migrations/00024.edgeql
integration-tests/lts/interfaces.test.ts
packages/generate/src/edgeql-js/generateInterfaces.ts

Wrap types in default module in `$default` namespace and re-export them at top level

---

packages/create/README.md
packages/create/src/recipes/express/README.md
packages/create/src/recipes/nextjs/README.md
packages/create/src/recipes/remix/README.md
packages/create/src/recipes/remix/index.ts
packages/create/src/recipes/remix/template/.eslintrc.cjs
packages/create/src/recipes/remix/template/app/routes/_index.__auth.tsx
packages/create/src/recipes/remix/template/app/routes/auth.__auth.$.ts
packages/create/src/recipes/remix/template/app/services.__auth/auth.server.ts
packages/create/src/recipes/remix/template/app/services.__auth/auth.ts
packages/create/src/recipes/sveltekit/README.md
packages/create/src/recipes/sveltekit/index.ts
packages/create/src/recipes/sveltekit/template/js/src/routes/+page.__auth.svelte
packages/create/src/recipes/sveltekit/template/js/src/routes/+page.server.__auth.js
packages/create/src/recipes/sveltekit/template/jsdoc/src/routes/+page.__auth.svelte
packages/create/src/recipes/sveltekit/template/jsdoc/src/routes/+page.server.__auth.js
packages/create/src/recipes/sveltekit/template/ts/src/routes/+page.__auth.svelte
packages/create/src/recipes/sveltekit/template/ts/src/routes/+page.server.__auth.ts

- I updated Readmes to use `yarn run create` instead of `yarn create` when running locally because yarn create is used for creating new projects from create starter kits, it will not run our create scripts but it expects create-starter-kit as an argument. 
Maybe I used something wrong, if this works on your side @jaclarke @scotttrinh I can revert this changes.
- Added auth files to Remix template since it was missing it.
- Updated Remix and Sveltekit index pages to show link to builtin UI if enabled.

Add Auth to Remix create & small fixes

---

packages/auth-core/package.json
packages/auth-core/src/consts.ts
packages/auth-core/src/core.ts
packages/auth-core/src/crypto.ts
packages/auth-core/src/index.ts
packages/auth-core/src/types.ts
packages/auth-core/src/utils.ts
packages/auth-core/src/webauthn.ts
packages/auth-core/test/crypto.test.ts

There are a few parts here due to how WebAuthn works:
- The "relying party" is the application itself, including both the web application server and the client.
- The "client" is the user's browser.
- An "authenticator" is a piece of software and/or hardware that is capable to generating and storing compatible credentials.
WebAuthn requires scripts that run on both the relying party server and client and that communicate back and forth with each other. The RP client gets an email to identify the user, and then sends that to the RP server, which responds with an "options" object. The RP client then triggers the authenticator "ceremony" (registration or authentication) it's trying to do, and sends that back to the RP server.
The RP server functionality is broken up into four methods on the …

Add WebAuthn sign in and sign up flows

---

integration-tests/lts/dbschema/default.esdl
integration-tests/lts/dbschema/migrations/00025.edgeql
packages/generate/src/builders.ts

Probably need tests, but wanted to get this up before the weekend.
Previously these FQNs
```edgeql
A::X::Y
B::X::Y
```
were emitted as:
```ts
import _X from './A/X';
import _X from './B/X';
```
now they are emitted as:
```ts
import _AX from './A/X';
import _BX from './B/X';
```
I opted to use `indentRef.name` instead of path logic.
It just seemed easier, but I understand this is a deviation.
I'm open to changing.
Previously these FQNs
```edgeql
A::B
A::B::C
```
were emitted as:
```ts
type __defaultExports = {
"B": typeof B;
"B": typeof _module__B;
};
```
Now these types & values are merged, just as in `generateIndex`.

Fix collision in QB with nested object & module names

---

.github/workflows/tests.yml
integration-tests/legacy/package.json
integration-tests/lts/package.json
integration-tests/nightly/package.json
integration-tests/stable/package.json
packages/auth-core/package.json
packages/auth-express/package.json
packages/auth-express/src/index.ts
packages/auth-nextjs/package.json
packages/auth-remix/package.json
packages/auth-sveltekit/package.json
packages/create/package.json
packages/driver/package.json
packages/edgeql-js/package.json
packages/generate/package.json

Adding some typechecking here to the tests CI so that we don't find out about these build failures on the release workflow.

Fix last import issue in auth-express

---

integration-tests/lts/casts.test.ts
packages/generate/src/syntax/cast.ts

Infer expression cardinality for Object UUID casts

---

packages/driver/src/baseClient.ts
packages/driver/src/conUtils.ts

I don't love the method or type alias names. Open to better/different ones.

Expose connection params via Client

---

integration-tests/lts/dbschema/queries/deepArrayInput.edgeql
integration-tests/lts/queries.test.ts
packages/driver/src/baseClient.ts
packages/driver/src/codecs/consts.ts
packages/driver/src/codecs/object.ts
packages/driver/src/reflection/analyzeQuery.ts
packages/driver/src/reflection/util.ts
packages/generate/src/queries.ts

- Moved `$.parseQuery` -> `Client.parse`. This feels better as it doesn't have to assume as much regarding client pool, options, or session.
Perhaps a name like `$parse` or `parse$` would be desired though?
- Added `$.util.parseCardinality` as a standard way to convert from the protocol number cardinality to the string enum used by the query builder.
Happy to move it where ever.
- `parse` returns a string enum `Cardinality` now rather than the protocol one.
This was the only spot the protocol cardinality leaked into type gen and it felt inconsistent in my (advanced) usage.
- Along those lines I removed the hardcoded protocol cardinality constants the codecs were using in favor of the cardinality enum.
And then the big refactor of `walkCodec`, now `generateTSTypeFromCodec`.
I broke down …

Refactor codec to TS generation for fine grained customization

---

packages/auth-core/src/errors.ts
packages/auth-core/src/webauthn.ts
packages/auth-remix/readme.md
packages/auth-remix/src/client.ts
packages/auth-remix/src/server.ts

Similar to #897 
Going to do some testing before opening this up for review, but it's a pretty straightforward port from the nextjs work.

Add WebAuthn and Magic Links in auth-remix

---

integration-tests/lts/dbschema/queries/exclusive.edgeql
integration-tests/lts/queries.test.ts

Add a test query to ensure queries generator generates the correct cardinality given a select filtering on an exclusive constraint.
Closes #930

Add test for exclusive filter in queries generator

---

integration-tests/lts/package.json
yarn.lock

Have had a lot of recent intermittent failures with running our type benchmarks. Might just remove them from CI, but for now, bump to the latest version.

Bump to latest @arktype/attest

---

.github/workflows/tests.yml

Benchmark has been failing on random CI runs, so going to keep it running, but not fail CI.

Do not fail CI on benchmark failues

---

integration-tests/legacy/package.json
integration-tests/lts/bench.ts
integration-tests/lts/package.json
integration-tests/lts/select.test.ts
integration-tests/nightly/package.json
integration-tests/stable/package.json
package.json
packages/auth-core/package.json
packages/auth-express/package.json
packages/auth-nextjs/package.json
packages/auth-remix/package.json
packages/auth-sveltekit/package.json
packages/create/package.json
packages/driver/package.json
packages/generate/package.json
packages/generate/src/syntax/literal.ts
packages/generate/src/syntax/path.ts
packages/generate/src/syntax/select.ts
packages/generate/src/syntax/typesystem.ts
yarn.lock

TypeScript 5.4 introduced a pretty significant regression in type performance with the `e.literal` expression. The changes here are meant to be no-op performance improvements.
Significant performance improvements observed in the latest benchmark tests:
- `e.literal: scalar`: -77.80%.
- `e.literal: array literal`: -45.89%
- `e.literal: named tuple literal`: -33.47%
- `e.tuple: named tuple literal`: -20.70%
- `e.literal: tuple literal`: -42.10%
- `e.literal: array of tuples`: -35.18%
Minor performance deltas were observed in other benchmarks, with most under 1% change from the baseline. Notably, `e.array: array of tuples` showed a -9.96% delta, and `params select` had a -6.34% delta.

Reduce type instantiations in `e.literal`

---

docs/insert.rst

This question has come up a few times on Discord, so thought I'd add an example to the query builder docs about composite constraints in `unlessConflict`

Add unlessConflict on composite constraint example

---

packages/auth-express/package.json
packages/auth-express/readme.md
packages/auth-express/src/index.ts
packages/auth-express/src/webauthn.ts

Similar to Next (#897) and Remix (#899)

Add WebAuthn and Magic Links in auth-express

---

integration-tests/lts/casts.test.ts
packages/generate/src/syntax/toEdgeQL.ts

Fixes #917.
I'm not sure when the inner exp would need to be wrapped in parentheses before casting, but I removed that.
Now wrapping the whole expression.
Also removing the parentheses wrapping for multiple cast siblings.

Adjust parentheses on QB cast rendering to fix pathing off of it

---

packages/auth-core/src/core.ts
packages/auth-express/src/index.ts
packages/auth-nextjs/src/app/index.ts
packages/auth-nextjs/src/pages/client.ts
packages/auth-nextjs/src/shared.ts
packages/auth-remix/src/server.ts
packages/auth-sveltekit/src/server.ts

Blocked by https://github.com/edgedb/edgedb/pull/7037
The current email verification flow always assumes that it ends in a PKCE code exchange. However, currently, if you send just the email, we do not start a PKCE flow, so it just ends in a redirect or `204 No Content` response. The above linked PR to the auth server allows specifying a `challenge` in the body along with the email which will trigger a PKCE flow.

Create PKCE session for verification with email

---

packages/driver/src/cli.mts

`npx` adds the current binary to the PATH in a way that confuses `which` so you end up calling the script in a recursive infinite loop.

Avoid calling self in a loop in `npx edgedb`

---

.github/workflows/release.yml

Looks like the official release action has been deprecated for a few years, and now it fails outright! Yay!
While I was in here, I decided to make the release process parallel.

Fix GitHub release action

---

integration-tests/lts/tsconfig.json
packages/generate/src/edgeql-js/generateInterfaces.ts

Types must be exported as `export type {}` instead of `export {}`.

Support `isolatedModules` in interfaces generator

---

packages/auth-express/readme.md
packages/auth-nextjs/readme.md
packages/auth-remix/readme.md
packages/auth-sveltekit/readme.md

[Node 18 requires passing a flag to enable the `globalThis.crypto` global](https://nodejs.org/docs/latest-v18.x/api/globals.html#crypto_1) which our PKCE generation code depends on. We used to shim this, but due to wanting to get away from using `require` directly, decided to drop the shim. We might reintroduce it, but in the meantime, we should note this so implementors are not left guessing about this issue.

Add note for Node 18 flag for crypto global

---

integration-tests/lts/package.json
packages/generate/src/queries.ts

Raises an error if the `params.types.cardinality` isn't a valid `Cardinality` enum member, rather than blissfully using `query`.

Ensure cardinality is a valid `Cardinality`

---

packages/driver/src/cli.mts

The typical path on macOS contains a space, but I was mostly testing the flow on linux/Docker where the path does not.

Properly quote binary path

---

packages/driver/src/cli.mts

Only log errors in the setup, or if the error that is thrown does not have a `code` which indicates it is some error other than one that the process has thrown.

Skip logging edgedb CLI errors in wrapper

---

.github/workflows/tests.yml
packages/driver/src/cli.mts
packages/driver/test/testUtil.ts

Some package managers, notably pnpm, but also npm with Windows, use scripts rather than links to link to the wrapper script, so the check to ensure we're not calling the wrapper recursively was not catching the self-reference since it was being called through the shell script.
Closes #974

Fix CLI wrapper loop when PM uses a shell script

---

packages/generate/src/edgeql-js/generateInterfaces.ts

We were using an obscure CommonJS syntax for what was essentially a type alias for the default modules and then exporting them in a large object-like export. Instead, just `export type` directly in the aliasing. Note the extra rebuilding of the nested namespace-modules: I couldn't find a clean way to re-export namespaces using ESM-only syntax.
I think the correct fix here is to use actual modules (like the query builder) and export an index, but we can look into that at a future date.
Closes #978 
---
In our integration test suite:
```ts
export type User = $default.User;
export type Person = $default.Person;
export type Hero = $default.Hero;
export type A = $default.A;
export type AdminUser = $default.AdminUser;
export type HasName = $default.HasName;
export type HasAge = $default.HasAge; …
```

Export default module interface types directly

---

docs/interfaces.rst

Hi,
Corrected the command name `... @edgedb/generate queries` to  `.. @edgedb/generate interfaces`

Fix Docs Interface Generator runtime command name

---

docs/generation.rst

Hi,
Corrects tab display, Bun tab is wrong, see ([link](https://docs.edgedb.com/libraries/js/generation#generators)) :

Fix Bun tab in Docs Generators

---

packages/driver/src/codecs/datetime.ts
packages/driver/src/codecs/ifaces.ts
packages/driver/src/codecs/memory.ts
packages/driver/src/codecs/range.ts
packages/driver/src/reflection/analyzeQuery.ts
packages/generate/src/queries.ts

This allows custom codecs to use imports from non-"edgedb" exports

Update queries generator to pull import path(s) from codecs

---

packages/create/src/recipes/nextjs/index.ts

It defaults to `no` in the official `create-next-app`.

Change default value for the src/ dir in create nextjs app

---

packages/ai/src/core.ts
packages/driver/package.json
packages/driver/src/browserClient.ts
packages/driver/src/fetchConn.ts
packages/driver/src/nodeClient.ts
packages/driver/src/rawConn.ts
packages/driver/src/retry.ts
packages/driver/src/utils.ts
packages/driver/test/client.test.ts
tslint.json

AI ext and all other exts except the 'auth' one go through authentication.
We extract driver's authenticated fetch into a reusable util.     
The util creates db path that it uses for the url, and adds headers to the fetch req.

Extract driver fetch configuration for reuse

---

packages/auth-core/src/core.ts

Does not actually test the validity of the JWT, but this is an optimistic measure meant to help client-side systems get relevant data like the expiration date from the token itself without having to round-trip to the auth server.
Also fixes a bug where the expiration time (which is in seconds) was being compared to `Date.now()` (which is in milliseconds), so was always going to be true.

Add static method to get a token expiration

---

.github/workflows/tests.yml

Now that 5.x is stable, remove references to it. Add direct reference to 4.x since that is no longer the version that the "stable" pointer points to.

Add 4 to testing matrix, removing pre-release 5.x

---

.github/workflows/tests.yml
packages/driver/src/cli.mts

Yarn Berry uses an even different scheme for running bin scripts: it unpacks the script into a temporary directory and adds that temporary directory into the shell's environment.
This mitigate is by far the most expensive, so it's used dead-last to avoid the overhead. Looks like on yarn 4.1.1, the call that succeeds takes an additional 140ms. Updated the call order and caching strategy to cache successful runs of the CLI (if it differs from the current cached value) to speed this up on multiple runs from newer Yarn invocations.

Test for hard-to-detect recursive CLI calls

---

packages/auth-express/src/index.ts
packages/auth-nextjs/package.json
packages/auth-nextjs/src/app/index.ts
packages/auth-nextjs/src/shared.ts
packages/auth-remix/src/server.ts
packages/auth-sveltekit/src/server.ts

Get the expiration date from the auth token and set the cookie to expire
when the token itself expires.
PKCE sessions are slightly different. In some contexts, we do not start
the session itself until a middle point in the flow, like with email
verification, the session starts on the auth server once the
verification token is _sent_ to the server, not when the email is sent
by the server to the email recipient. Since the verification token has a
lifespan of 24 hours at the moment, the expiration is longer than the
PKCE session lifespan which is currently 10 minutes. So instead of
trying to chase the smallest window of time we can, we set it to a
reasonable level: one week after which the PKCE verifier cookie is
expired, requiring whatever flow has begun to be retried.
Closes #990

Expire cookies with token or PKCE TTL

---

packages/auth-express/src/index.ts
packages/auth-remix/src/client.ts
packages/auth-remix/src/server.ts
packages/auth-sveltekit/src/client.ts
packages/auth-sveltekit/src/server.ts

Mirrors the change in #938 for the other framework helpers.
Closes #937

Set Cookies to Secure if app baseUrl is https

---

packages/auth-express/src/index.ts
packages/auth-nextjs/src/shared.ts
packages/auth-remix/src/server.ts
packages/auth-sveltekit/src/server.ts

Since there are some cases where we are navigating from links, we need to use `lax` as our SameSite.

Set auth cookies to be `SameSite: lax`

---

packages/generate/src/cli.ts
packages/generate/src/edgeql-js.ts

Facilitate skipping the prompt to update gitignore file for the generated query builder code. We should always check for `isTTY` before prompting, and also added an option to explicitly opt out of checking.
Closes #985

Add option to skip updating ignore file

---

packages/driver/src/errors/base.ts
packages/driver/src/rawConn.ts
packages/driver/src/transaction.ts
packages/driver/test/connection.test.ts

`Error.cause` is now supported across all of our supported platforms. Use that instead of the custom `source` property.
See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/cause)

Replace `Error.source` with standardized `cause`

---

packages/generate/src/queries.ts

A small tweak easing migration to `importMap`
Mark both as optional so both old & new `analyzeQuery` can be used as input.

Mark generateFiles imports as optional

---

packages/driver/src/adapter.deno.ts
packages/driver/src/adapter.node.ts
packages/driver/src/primitives/buffer.ts
packages/driver/test/deno.test.ts

Instead of manually implementing the base64 encoding when the buffer
global is not defined, explicitly import `node:buffer` in both the
node-like case, and the deno-like case.
Closes #1003 
Note about 1003: This doesn't _directly_ address the issue with Cloudflare Workers but it kind of leans into the fact that we already depend on their Node compatibility shim anyway. Once we get around to supporting WinterCG-like runtimes more directly, we'll work on that more directly.

Use Node compatibility for Deno Buffer

---

.github/workflows/tests.yml
packages/driver/package.json
packages/driver/src/cli.mts
yarn.lock

Passing quoted arguments to the wrapper CLI was getting unwrapped and
unquoted when they show up as arguments in the CLI itself. We need to
re-escape and re-wrap the strings when passing them to the underlying
CLI binary.

Use shell-quote to properly quote commands

---

.github/workflows/release.yml

GitHub now has a pretty good implementation built in that is pretty
flexible, so we will use that from now on.

Remove the changelog generation from release

---

integration-tests/lts/dbschema/queries/freeShape.edgeql
integration-tests/lts/queries.test.ts
packages/generate/src/queries.ts

These show up in regular expressions, so do a blanket find-and-replace to a quadruple backslash.
Closes #878

Escape double-backslashes in EdgeQL

---

packages/auth-sveltekit/src/client.ts
packages/auth-sveltekit/src/server.ts

I tested this with example sveltekit and it works. 
I retested and it works, but not sure is the setCookie function definition the best, especially the params it needs, doesn't look very pretty.

Add webauth & magic links to sveltekit

---

.github/workflows/tests.yml
packages/driver/src/cli.mts

Since we are now quoting the arguments directly in the `runEdegDbCli` function, we do not need to quote this argument manually.

Do not manually quote install-dir command

---

integration-tests/lts/select.test.ts

Came up in a troubleshooting session and thought it would be worth keeping the test.

Add test for FreeObject with nested select

---

.github/workflows/release.yml

We were using `\` before, but that was ending up in the actual string, so I thought maybe we could omit it. Nope! This should work.

Properly quote release name for `@` literal

---

integration-tests/lts/bench.ts
integration-tests/lts/select.test.ts
packages/generate/src/syntax/typesystem.ts

Previously, if you made a select expression with a constant or coalescing expression, we _always_ calculated the cardinality of a object key based on the pointer's cardinality, rather than allowing you to return something _assignable_ to that cardinality. This change will check if the assignment is possible, and override the cardinality when converting the query builder expression to a TS type.

Use given cardinality in select expression

---

integration-tests/lts/select.test.ts
packages/generate/src/syntax/external.ts
packages/generate/src/syntax/select.ts
packages/generate/src/syntax/typesystem.ts

We were "faking" a `TypeSet` as part of the return type of `e.shape` to allow using `$infer` on `e.shape` expressions, but it turns out that caused the recent change to allow setting properties on a shape to a `TypeSet` as long as it agrees with the cardinality of the pointer to break.
There are some lingering issues here that we should clean up, such as making the cardinality of `$infer<typeof someShape>` something reasonable rather than trying to infer it from the shape since that will depend on it's actual usage. In practice, most people want the `Cardinality.ONE` version (so, without `null` and not an array) so perhaps we can change this in a break version in the future.

Fix `$infer` for `e.shape`

---

.github/workflows/tests.yml
integration-tests/lts/select.test.ts
packages/generate/src/syntax/select.ts
packages/generate/src/syntax/typesystem.ts

Type intersection creates an expression with a fixed `__shape__` expression. This was being glossed over before because the parameter type was `unknown`, but once we switched it to match the scopified object expression, it became too strict for use with intersections.
Closes #856

Loosen type of `e.shape`'s returned scope

---

integration-tests/lts/select.test.ts
packages/generate/src/syntax/select.ts
packages/generate/src/syntax/typesystem.ts

Introduces a type-level marker to the return value of the $shape function. This marker is used solely for type inference to carry element, cardinality, and shape information and is not present at runtime.
We now detect this specific construct in the `setToTsType` (which is the actual type we alias as `$infer`) and just short-circuit to calculating the object shape as if the shape was wrapped in a select.

Use specific type-level marker to `e.shape`

---

integration-tests/lts/dbschema/default.esdl
integration-tests/lts/dbschema/migrations/00026-m1wb2dg.edgeql
integration-tests/lts/interfaces.test.ts
integration-tests/lts/objectTypes.test.ts
integration-tests/lts/select.test.ts
packages/generate/src/syntax/typesystem.ts

Hey, I am not sure if this is 100% what we need in order to fix #1037 .
It works okay with the test mentioned in the issue.

Remove from object shape keys with value never

---

.github/workflows/tests.yml
integration-tests/legacy/package.json
integration-tests/lts/package.json
integration-tests/nightly/package.json
integration-tests/stable/package.json
package.json
packages/ai/package.json
packages/auth-core/package.json
packages/auth-express/package.json
packages/auth-nextjs/package.json
packages/auth-remix/package.json
packages/auth-sveltekit/package.json
packages/create/package.json
packages/driver/package.json
packages/generate/package.json
packages/generate/src/syntax/group.ts
packages/generate/src/syntax/modules/std.ts
yarn.lock

Add types for `$FreeObjectλShape`  and `$str` in `packages/generate/src/syntax/modules/std.ts` which will fix type of `$expr_Group` which will fix type of `SomeExpression`.
```
export type $FreeObjectλShape = any;
export type $str = ScalarType<"std::str", string>;
```

Update TS version in the monorepo

---

README.md
package.json

Now that we use turborepo for running monorepo tasks, update the README to indicate that you should use the new turborepo powered run scripts.

Update README for turborepo

---

.github/workflows/tests.yml

A recent update of pnpm (9.8.0) started to cause failures. I believe this is due to the "temporary" projects being made within the main repo's directory, causing some weird "project" detection in pnpm.

Use temporary directory for CLI test

---

packages/driver/package.json

A little extra churn in `package.json` from running yarn to update the version
field, which had the side effect of rearranging the dependencies.

Release `edgedb` 1.5.10

---

docs/index.rst
packages/driver/src/conUtils.ts
packages/driver/src/rawConn.ts
packages/driver/test/connection-config.test.ts

I will try to add these tomorrow:
Documentation is missing:
- SNI,
- Cloud Profile,
- tlsCA maybe should be documented too,
- `credentials` is not documented.
**More things to be done**: add SNI to credentials.json in the cli, and later read it from there: `Oh and to address this specifically, although very marginal, we may want to update the CLI to include tls_server_name in credentials.json if --tls-server-name was specified while linking an instance.`
Atm CLOUD_PROFILE is taken from env var when using options. And when using env vars it is not used at all?

Add support for SNI when connecting to the instance

---

packages/driver/src/cli.mts

This is apparently the case in Vercel build containers.

Add -y confirmation to CLI wrapper self-install

---

packages/auth-express/src/index.ts
packages/auth-nextjs/src/shared.ts
packages/auth-remix/src/server.ts
packages/auth-sveltekit/src/server.ts

When `require_verification` is false (which is the case here), we should not delete the PKCE session since we still need it for verifying emails even though it's not required. We still send the email, and the verification flow requires that the same PKCE session is valid in the browser.
Closes #1094

Keep verifier cookie in built-in signup

---

integration-tests/lts/insert.test.ts
integration-tests/lts/literals.test.ts
integration-tests/lts/select.test.ts
packages/generate/src/syntax/toEdgeQL.ts

Input data is likely to contain the string `"$$"`, so use an interstitial label to make it less likely to collide with typical JSON data.
Closes #1097

Use more robust raw string quoting

---

integration-tests/lts/select.test.ts
packages/generate/src/syntax/toEdgeQL.ts

This was refactored a few times along the way during working on this
fix, and we merged it without actually passing the stringified value to
the final result.

Use stored stringified JSON value

---

packages/auth-sveltekit/src/server.ts

The built in authentication flow with sveltekit is broken due to a missing verifier cookie.
Aligned with nextjs implementation, see https://github.com/edgedb/edgedb-js/blob/b9ddf43bed64eb5a356584396c11244bf854aec6/packages/auth-nextjs/src/shared.ts#L514C48-L514C56

Fix sveltekit built in authentication flow due to missing verifier cookie

---

packages/auth-sveltekit/src/server.ts

In the sveltekit auth helper, we accidentally defined `onMagicLinkCallback` as a required method instead of an optional callback handler.

Fix accidental required magic link callback

---

packages/driver/src/baseClient.ts
packages/driver/src/baseConn.ts
packages/driver/src/errors/base.ts
packages/driver/src/errors/resolve.ts
packages/driver/src/errors/tags.ts
packages/driver/src/index.node.ts
packages/driver/src/options.ts
packages/driver/src/transaction.ts
packages/driver/test/client.test.ts

See https://github.com/edgedb/edgedb/issues/7822 for details.

Add warnings handler

---

package.json
packages/auth-nextjs/package.json
packages/auth-nextjs/src/app/index.ts
packages/auth-nextjs/src/shared.ts
yarn.lock

This PR adapts the `@edgedb/auth-nextjs` package for the [kinda*] breaking change of Next.js 15, where [Request APIs like `cookies` and `params` are now async](https://nextjs.org/blog/next-15#async-request-apis-breaking-change).
To solve this, i simply added `await` to all corresponding places. Awaiting something sync is not strictly a noop, but for these cases it shouldn't change behavior afaict.
**Tested** in my own project with both Next.js before their breaking change and after it.
**Breaking change:** As `NextAppAuth.getSession()` has to await `cookies()`, it is now an `async` function, which means those upgrading have to add `await` when calling it.
```diff
const auth = createAuth(client, {
baseUrl: `http://localhost:${process.env.PORT || 3000}`,
authCookieName: "edgedb-session", …
```

[auth-nextjs] Async Request APIs, compat with Next.js 15

---

packages/auth-core/src/core.ts
packages/auth-nextjs/src/shared.ts

If your database is deployed to a private network and is not available at a public URL, this adds the ability to drive the whole flow from your application server, delegating to the auth server from your application server.
---
When testing this manually, I set up a new route handler at `/auth/oauth` that shadows the one built into our `createAuthRouteHandlers` behavior like this:
```ts
export async function GET(request: NextRequest): Promise<NextResponse> {
const callbackUrl = new URL("auth/server/oauth/callback", authConfig.baseUrl);
const authorizeUrl = new URL(
"auth/server/oauth/authorize",
authConfig.baseUrl,
);
request.nextUrl.searchParams.set("callback_url", callbackUrl.toString());
request.nextUrl.searchParams.set("authorize_url", authorizeUrl.toString());
return await …
```

Add ability to specify OAuth endpoints

---

packages/driver/src/baseClient.ts
packages/driver/src/baseConn.ts
packages/driver/src/options.ts
packages/driver/test/browser.test.ts

Depends on https://github.com/edgedb/edgedb/pull/8036

Add support for query tagging

---

integration-tests/lts/update.test.ts
packages/generate/src/syntax/toEdgeQL.ts

Reported on discord: https://discord.com/channels/841451783728529451/1313928437886619738
Fix 1:
While debugging realised the original query is incorrect: the expressions being added to the `with` block can't reference the select expression the with block is attached to, as that select can't be hoisted into a var in it's own with block. The expression tree walker was not checking for this case (an expr's parent also being one of its child exprs), which could cause an infinite loop in `toEgdeQL`.
Fix 2:
We check in `toEdgeQL` that all the places where a repeated expr is used exist within the scope of the with block it's being hoisted to. Here we were incorrectly not considering expressions already explicitly bound to that with block to be valid scopes.

Fix some bugs in toEdgeQL when using `e.with`

---

.github/workflows/release.yml
.github/workflows/tests.yml
integration-tests/legacy/gel.toml
integration-tests/lts/gel.toml
integration-tests/nightly/gel.toml
integration-tests/stable/gel.toml
packages/driver/test/testUtil.ts
packages/generate/gel.toml
turbo.json

CLI still doesn't recognise [gel] inside gel.toml.  So I updated our `gel.toml` files inside test folders to use `egdedb`.
Do we want to run some CI tests on Windows machines? All tests we have run on ubuntu.
At the end I reverted tests to use `edgedb` for the CLI (`edgedb migrate` etc...) in order to use the current `setup-edgedb` action.

Update github workflows

---

packages/driver/src/reflection/queries/types.ts

This fixes a warning in 6.0 where we warn if you have a filter clause that has a cardinality of many.
Fixes the error:
"possibly more than one element returned by an expression in a FILTER clause"

Fix cardinality issue in type reflection query

---

.github/workflows/tests.yml

Also shuffles the test matrix a bit to update Node release support.
18 is now in maintenance, so spend less time testing it. Add 23 to the matrix to test the latest stable with the upcoming Node release.

Add server v6 to CI

---

packages/driver/src/cli.mts
packages/driver/src/typeutil.ts

1. Do not prompt for confirmation when installing the CLI, even for TTYs
2. More gracefully handle errors from the CLI. `stderr` is already being
piped to the parent process, so no need to log errors so loudly.

Make CLI wrapper install quieter

---

.github/workflows/tests.yml
packages/gel/src/cli.mts

Now that the package is called `gel`, we need to switch to checking `gel` in argv. Along with this change are a few more actual logical changes:
1. Prefer `PATH` to find the binary instead of the cached location.
2. _Only_ check for the command we're wrapping when using `which` to find the path to the CLI binary.

Update CLI wrapper for `gel` command

---

packages/codemod/package.json
packages/codemod/tsconfig.json

npm printed the following warnings when publishing:
npm warn publish npm auto-corrected some errors in your package.json
when publishing. Please run "npm pkg fix" to address these errors.
npm warn publish errors corrected:
npm warn publish "bin" was converted to an object
npm warn publish "bin[@gel/codemod]" was renamed to "bin[codemod]"
npm warn publish "bin[codemod]" script name was cleaned
npm warn publish "repository.url" was normalized to "git+https://github.com/edgedb/edgedb-js.git"

Fix some package.json publish warnings from npm

---

.github/workflows/release.edgedb.yml

Each alias package needs the OG package to be built, so just let turbo build all of the packages first.

Use turbo to build all packages

---

packages/create/src/recipes/express/index.ts
packages/create/src/recipes/nextjs/index.ts
packages/create/src/recipes/remix/index.ts
packages/create/src/recipes/sveltekit/index.ts

We should consider using a more robust way of managing these ranges to avoid needing to always touch these directly, while also avoiding making them roughly "*".
This only "broke" because we don't have these old versions published and `^` for 0.x versions won't automatically install the latest minor version since that's considered a breaking change.

Use correct package ranges in create recipes

---

integration-tests/lts/tsconfig.json
package.json
packages/gel/src/reflection/queries/functions.ts
packages/gel/src/reflection/queries/operators.ts
packages/generate/src/cli.ts
packages/generate/src/edgeql-js/generateCastMaps.ts
packages/generate/src/edgeql-js/generateFunctionTypes.ts
packages/generate/src/edgeql-js/generateInterfaces.ts
packages/generate/src/edgeql-js/generateObjectTypes.ts
packages/generate/src/edgeql-js/generateOperatorTypes.ts
packages/generate/src/edgeql-js/generateScalars.ts
packages/generate/src/funcoputil.ts
packages/generate/src/gel-prisma.ts
packages/generate/src/genutil.ts
packages/generate/src/queries.ts
packages/generate/src/syntax/hydrate.ts
packages/generate/tsconfig.json
yarn.lock

Many places in the code were using unchecked indexed access, which conflicts with many people's TypeScript configurations. We copy the hydrate.ts module directly into the generated code, so we will now check the rest of the generate package with the same strict configuration.
An alternative approach would be to separate out the code we copy into the query builder into a more strict subset and keep the looser config for our own code, but I think stricter is better anyway.
Most places just got the assertion treatment, but in a few places it was straightforward enough to actually do something more safe.

Require explicit index checks or assertions

---

integration-tests/lts/dbschema/default.esdl
integration-tests/lts/dbschema/migrations/00029-m1saaen.edgeql
integration-tests/lts/dbschema/migrations/00030-m14ccrz.edgeql
integration-tests/lts/objectTypes.test.ts
packages/generate/src/builders.ts

This regressed in https://github.com/geldata/gel-js/pull/900 due to not having a good test case. The way to reproduce this issue is to ensure that the module ends up as something that the `schema` module would need to import, and it seems like that requires object types defined in these edge case modules.

Fix module names that are not valid identifiers

---

packages/gel/src/index.node.ts
packages/gel/src/index.shared.ts
packages/gel/src/options.ts

Idk if actually moving the options exports to shared helps the browser index at all. I suspect not, since it's gone this long without. They've probably never been needed at runtime.
Regardless, this feels more correct, and it is saner to reason about too internally IMO.

Export WarningHandler type / Share options exports with browser index

---

packages/gel/src/fetchConn.ts
packages/gel/test/client.test.ts

Currently the UI can't show query warnings as `rawParse`/`rawExecute` don't return them. Also just return the whole return values array from the internal `_parse` method in `rawParse` instead of re-ordering it for no real reason.

Return query warnings from the `rawParse/Execute` methods used by UI

---

packages/gel/src/options.ts
packages/gel/test/client.test.ts

It is more idiomatic to merge a list of errors with `AggregateError.errors` rather than `Error.cause`.
For logging, giving the original error to the wrapped one in `cause`, causes the error & stacktrace to be duplicated/nested on the console.

Adjust default warning handlers for DX

---

packages/gel/src/baseClient.ts
packages/gel/src/reflection/analyzeQuery.ts
packages/gel/src/reflection/index.ts
packages/gel/test/client.test.ts

`client.describe()` (renamed from `client.parse()` for consistency with
other drivers) now returns the Capability bitmask.

Expose query capabilities in `client.describe()` and `analyzeQuery`

---

packages/ai/src/core.ts
packages/ai/src/utils.ts

We were accidentally fire-and-forgetting this promise rather than awaiting it and letting it reject the outer promise.
Will be introducing more strict linting rules to catch cases like this soon.

Ensure error response handler rejects outer error

---

packages/ai/src/core.ts

The name of this property changed during the development of the ai
extension, and in the latest verison, we dropped support for shadowing
the same value across both names, so this is now an error.
Also use the same error handling code from the RAG querying code.
Closes #1232

Fix backwards incompatible change in ai extension

---

packages/auth-core/src/core.ts
packages/auth-core/src/types.ts

In 6.0, we started returning the identity_id from signup even if email verification was required. This allows developers to create User objects connected to the newly created identity, even before the User verifies their email. It also allows developers to treat "missing PKCE" in the email verification flow as a success state that requires the end user to simply sign in again. This was difficult to do before because we treated the verification flow as the end of the "sign up" flow, but if you want to allow no-PKCE verification, you need to sign up the user before verification is complete.

Return identity_id, if available, from signup

---

.github/workflows/tests.yml
packages/gel/src/cli.mts

- Drop the index lookup and assemble the CLI package URL directly.
- Add support for `win32` platform.
- Drop `-gnu` libc: this was never used and we don't build for it.

Match CLI package logic to Python wrapper

---

packages/gel/src/index.node.ts
packages/gel/src/index.shared.ts

In general, we want to expose all types and classes that end users actually interact with, so this is an attempt to explicitly export _more_ of those.

Export more types and classes from `gel` package

---

integration-tests/lts/select.test.ts
packages/generate/src/syntax/path.ts
packages/generate/src/syntax/with.ts

When using `filter_single` with `e.op` in select or update, we wrap the output select/update expr in an `assert_single()` call to ensure type correctness, but lie to the typesystem that the returned expression is still a select/update expr.
So when one of these wrapped select/update expressions is passed to `e.with` as the `expr` arg, it gets tripped up by the expr actually being an assert_single function expression instead of a 'withable' expr, and fails to attach the refs to the with block of the wrapped select/update expr, generating broken queries.
This PR updates `e.with` to handle `assert_single` wrapped select/update exprs by moving the `assert_single` to wrap the whole `with` expr, so refs are correctly attached to the inner select/update expr by `toEdgeQL`.

Fix handling of assert_single wrapped select/update exprs when used as e.with expr

---

.github/workflows/tests.yml
integration-tests/lts/package.json
integration-tests/lts/testRunner.ts
integration-tests/lts/throughput.bench.mts
yarn.lock

Make it easier to ensure we don't regress query throughput when making changes to low-level query code. No automatic guard rails here, but having the script run in CI at least gives us the opportunity to check.

Add benchmark for query throughput

---

packages/gel/src/baseConn.ts
packages/gel/src/options.ts
packages/gel/src/transaction.ts
packages/gel/test/transaction.test.ts

If an explicit isolation level and/or access mode is set in the transaction options, set the corresponding default transaction options that controls implicit transactions to this explicit value.

Set default transaction options from `withTransactionOptions`

---

packages/create/src/utils.ts

It was turning space-separated commands (like `pnpm dlx`) into a single quoted call like `'pnpm dlx'`. Move the runner command out of the quoting to avoid that quoting

Do not quote "runner" command

---

integration-tests/lts/insert.test.ts
packages/generate/src/syntax/with.ts

discussed in Slack with Scott - insertUnlessConflict should be `Withable` also
there actually weren't any previous tests explicitly testing `insert` is `withable`, but added one anyway for `unlessConflict`

Fix type error when e.with() wraps unlessConflict()

---

packages/auth-nextjs/src/shared.ts

When I refactored the OAuth flow to allow proxying through the application server, I changed the behavior of the default authorize endpoint to point at the application server but did not add a default handler there to call through to the server and get the correct authorize endpoint to redirect the user's browser to the IdP.

Add missing /oauth/authorize passthrough endpoint

---

packages/auth-core/src/core.ts
packages/auth-core/src/types.ts

We added this in v6 along with the `identity_id`.

Add provider ID token to TokenData type

---

integration-tests/lts/dbschema/default.esdl
integration-tests/lts/dbschema/migrations/00031-m1hbukk.edgeql
integration-tests/lts/gel.toml
integration-tests/lts/insert.test.ts
integration-tests/lts/interfaces.test.ts
packages/generate/src/syntax/toEdgeQL.ts

Fixes #788, and should also fix #679

Fix handling of inserts with both unless conflict and a with block

---

packages/gel/src/reflection/analyzeQuery.ts

Different instances can produce different field orders for Object codecs, so we should have an fully ordered sorting algorithm to stabilize the order. This should help codegen to be deterministic, or at least get us a little closer.
The sorting is now grouped in a logic manner like this:
- Required single properties
- Optional single properties
- Required multi properties
- Optional multi properties
- Required single links
- Optional single links
- Required multi links
- Optional multi links
Within those groups, fields are sorted by name.
---
After:
```ts
export type GetMoviesStarringReturns = Array<{
"id": string;
"local_date": LocalDate;
"range": Range<number>;
"release_year": number;
"title": string;
"tuple": [number, string, Array<bigint>];
"version": {
"major": number;
"minor": …
```

Stabilize `queries` generated object typedefs

---

packages/auth-nextjs/src/shared.ts

This fixes the signout route not actually deleting the auth cookie. In newer versions of Next.js, getting the cookie store is async, so this used to work, but when we fixed support for async cookies in Next.js > 15, we missed this one callsite.

Await deleting the auth cookie

---

packages/gel/src/codecTypeRegistry.ts
packages/gel/src/index.shared.ts
packages/gel/src/reflection/analyzeQuery.ts
packages/generate/src/cli.ts
packages/generate/src/commandutil.ts
packages/generate/src/queries.ts

This PR adds the ability for users of the queries generator to override the TypeScript types of custom scalar variables via `OverrideCodecType`. The default scalar types are non-overrideable.
Example:
1. Set up a schema and a query:
`default.gel`:
```
module default {
scalar type EvmAddress extending str {
constraint expression on ( re_test(r'^0x[a-f0-9]{40}$', __subject__) );
}
scalar type HumanAge extending int16 {
constraint max_value(120);
}
type User {
required property primaryAddress -> EvmAddress {
constraint exclusive;
};
required property firstName -> str;
property username -> str {
constraint exclusive;
};
property age -> HumanAge;
}
}
```
`findUser.edgeql`:
```
select User {
id,
primaryAddress,
username,
age
} filter .id = <uuid>$id
```
2. Run `generate queries --target ts …

feat: allow users to customize the TypeScript type of a custom scalar
