src/codecs/registry.ts
Depends on [PR in edgedb](https://github.com/edgedb/edgedb/pull/1031)
=> All strings in type descriptors are 32 bit now

test/globalSetup.ts
Update `ROLE` and `Auth` settings to use options that are valid in the
latest version of EdgeDB.
=> tests: Fix test database setup.

src/client.ts, test/client.test.ts
=> Complain when concurrent operations are run on the same connection

docs/usage.rst, src/codecs/namedtuple.ts
=> Fix error message and doc example

src/codecs/namedtuple.ts, src/codecs/object.ts, src/codecs/tuple.ts, src/datatypes/introspect.ts, src/datatypes/namedtuple.ts, src/datatypes/object.ts, src/datatypes/set.ts, src/index.shared.ts, test/client.test.ts
AND drop some accidental code duplication
=> Add basic introspection API (private for now)

src/buffer.ts
=> Fix write buffer resizing to update the size of the internal buffer

src/client.ts, src/pool.ts, test/client.test.ts, test/pool.test.ts
See https://github.com/edgedb/edgedb-python/issues/51 for
the relevant discussion.
=> Rename "fetch*" methods to "query*"

README.md
As Yury suggested in https://github.com/edgedb/edgedb/pull/1531
=> Replace Spectrum badge with GitHub discussions

docs/usage.rst, src/pool.ts
Follow-up after 23057bbeb346b867c2c8a405058d9ede1d67640d
=> Docs: s/AwaitConnection/Connection/

test/globalSetup.ts
Previously tests just exit without reporting any progress or failing
tests.
=> tests: report error on early EdgeDB exit

src/codecs/datetime.ts, src/codecs/registry.ts, src/compat.ts, src/datatypes/datetime.ts, src/datatypes/dateutil.ts, test/client.test.ts
Related issue: https://github.com/edgedb/edgedb/issues/1769#issuecomment-692379938
=> Add EdgeDBDateTimeCodec

src/client.ts, src/ifaces.ts, src/pool.ts
=> Move request methods into Executor interface

src/client.ts, test/client.test.ts
=> Updated protocol and duration format

src/buffer.ts, src/client.ts, src/legacy_transaction.ts, src/transaction.ts, test/client.test.ts
This is based on #90  and #84 so look at latest commit only.
=> Execute statement disabling transactions

src/client.ts, src/ifaces.ts, src/index.node.ts, src/legacy_transaction.ts, src/options.ts, src/pool.ts, src/transaction.ts, test/client.test.ts, test/legacy_transaction.test.ts, test/pool.test.ts, test/retry.test.ts, test/transaction.test.ts
This is the JavaScript counterpart of edgedb/edgedb-python#174
=> Transaction options part of RFC1004

tools/compileForDeno.ts
=> Actually fix deno release workflow

.github/workflows/tests.yml, test/deno.test.ts, test/globalSetup.ts, test/globalTeardown.ts, tools/compileForDeno.ts
Run tests on windows as well as linux.
=> add windows to github CI

src/client.ts, src/codecs/registry.ts, src/ifaces.ts, test/client.test.ts
Changes ported from https://github.com/edgedb/edgedb-python/pull/195
=> Implement support for protocol version 0.11

src/con_utils.ts, src/credentials.ts, src/platform.ts
Copies changes from https://github.com/edgedb/edgedb-python/pull/197
=> Use system config dir instead of ~/.edgedb

src/con_utils.ts
see https://github.com/edgedb/edgedb-js/pull/117#discussion_r672468857
=> remove `in` operator usages

qb/RFC.md, qb/edgedb.toml, qb/playground.ts, qb/test/select.test.ts, src/reflection/typesystem.ts, src/syntax/select.ts, src/syntax/toEdgeQL.ts
Cardinality inference in `.filter` is not yet implemented
=> Implement filter, orderby, offset, limit

docs/api/connection.rst, docs/api/types.rst, docs/usage.rst, src/client.ts, src/ifaces.ts, src/pool.ts, src/transaction.ts, test/client.test.ts, test/deno.test.ts, test/globalSetup.ts, test/pool.test.ts, test/retry.test.ts, test/transaction.test.ts
And queryOneJSON() to querySingleJSON()
=> Rename queryOne() to querySingle()

src/pool.ts
All the query and transaction methods on Pool used `run()`, `acquire()`, and `release()` in their implementations. This caused a bunch of irrelevant warnings to be printed when using undeprecated methods.
=> Don't print unrelated deprecation warnings

qb/playground.ts, qb/test/casts.test.ts, qb/test/operators.test.ts, qb/test/paths.test.ts, qb/test/select.test.ts, qb/test/sets.test.ts, src/reflection/generate.ts, src/reflection/generators/generateCastMaps.ts, src/reflection/generators/generateObjectTypes.ts, src/reflection/generators/generateRuntimeSpec.ts, src/reflection/generators/generateScalars.ts, src/syntax/funcops.ts, src/syntax/path.ts, src/syntax/select.ts
Improve type inference
Fix `BaseObject` bug
=> Improve type inference

.github/workflows/tests.yml, src/client.ts, src/codecs/codecs.ts, src/codecs/consts.ts, src/codecs/object.ts, src/codecs/registry.ts
Addjust codec types to support protocol version 0.12.
=> Support protocol version 0.12

src/client.ts, src/con_utils.ts, test/connection.test.ts
The `waitUntilAvailable` set to 30 seconds by default makes the
`connect()` call to retry connecting multiple times, until either the DB
is available ot the timeout is hit. This can create an impression that
"edgedb.connect()" is hung indefinitely. Fix this by prninting a warning
to stderr explaining what is happening.
The warning also suggests to try `connect()` without arguments if the
program is run within a directory created with `edgedb project init` yet
`connect()` was called with explicit arguments.
=> Show a clear warning when we're waiting for the DB to become available

docs/index.rst
Related to intersphinx PR: https://github.com/edgedb/edgedb.com/pull/374
=> Add docs intro ref

src/con_utils.ts, test/connection.test.ts
=> Fix handling of `EDGEDB_CLIENT_SECURITY` env var

docs/api/connection.rst, docs/usage.rst
Related to https://github.com/edgedb/edgedb/pull/3039
=> Docs reorg

qb/test/collections.test.ts, qb/test/select.test.ts, src/reflection/hydrate.ts, src/reflection/path.ts, src/reflection/typesystem.ts, src/syntax/funcops.ts, src/syntax/path.ts, src/syntax/select.ts, src/syntax/toEdgeQL.ts
The querybuilder should now generate correct edgeql for queries with link props, but those queries currently cause an ISE (https://github.com/edgedb/edgedb/issues/3245), so are skipped in tests for now.
=> More querybuilder fixes

package.json, qb/.gitignore, qb/package.json, qb/playground.ts, qb/test/delete.test.ts, qb/test/select.test.ts, qb/tsconfig.build.json, src/reflection/path.ts, src/reflection/typesystem.ts, src/syntax/cast.ts, src/syntax/select.ts
Fix pathify for computables
Remove cardinality inference/modification from modifier methods
=> Excessively deep fix

docs/driver.rst
Misspelled import statement in ES Module section
=> FIX Typo in Typescript/JS Driver Docs

src/reflection/generate.ts
=> Fix ESM gen bug

docs/literals.rst, package.json, qb/playground.ts, qb/test/collections.test.ts, qb/test/literals.test.ts, qb/test/select.test.ts, src/reflection/generators/generateScalars.ts, src/reflection/hydrate.ts, src/reflection/typesystem.ts, src/syntax/funcops.ts
=> Implement new enum syntax

src/errors/base.ts
=> Add `name` getter on `EdgeDBError`

docs/select.rst, package.json, qb/playground.ts, qb/test/objectTypes.test.ts, qb/test/select.test.ts, qb/test/setupTeardown.ts, src/reflection/path.ts, src/syntax/path.ts
Usage
```ts
const query = e.select(e.Movie, () => ({
...e.Movie["*"],
}));
```
=> Select star

qb/test/select.test.ts, src/syntax/toEdgeQL.ts
=> Correctly quote backlink keys in shapes

qb/dbschema/default.esdl, qb/dbschema/migrations/00007.edgeql, qb/test/insert.test.ts, qb/test/select.test.ts, qb/test/setupTeardown.ts, src/syntax/toEdgeQL.ts
=> When selecting a required multi link, wrap expr in `assert_exists` guard

src/transaction.ts
Fixes the name of the `queryRequiredSingle` op in transactions
=> fix copy-pasta bug

src/codecs/datetime.ts, src/conUtils.ts, src/datatypes/datetime.ts, src/retry.ts, src/syntax/range.ts, test/connection.test.ts
=> Add support for `EDGEDB_WAIT_UNTIL_AVAILABLE` env var

docs/insert.rst
Sets a missing code block language highlight.
Closes  edgedb/edgedb#3940
=> fix: set code block highlight language

docs/select.rst
This one threw me for a loop. Hopefully this is helpful for others.
=> Add Filter on link properties example.

README.md
Fixes my previous PR (#416) also introducing invalid syntax to the group example.
Also fixes a couple other issues I found along the way, hopefully we're set after this.
=> Another set of README fixes

qb/playground.ts, qb/test/collections.test.ts, src/reflection/generators/generateScalars.ts, src/reflection/typesystem.ts
Expose tuple of enum values.
```ts
e.Genre.__values__; //  ["Horror", "RomCom", "Action"]
```
=> Strongly type __values__ on EnumType

qb/test/group.test.ts, qb/test/select.test.ts, qb/test/sets.test.ts, qb/test/with.test.ts, src/syntax/toEdgeQL.ts
=> Fix scope var name generation

docs/queries.rst
I believe this code sample doesn't belong here and might cause confusion for newcomers
=> typo: unintended code sample

docs/interfaces.rst, docs/queries.rst, docs/querybuilder.rst
Depends on https://github.com/edgedb/edgedb.com/pull/538
=> Fix codetab captions

packages/driver/src/reflection/queries/types.ts, packages/generate/dbschema/default.esdl, packages/generate/dbschema/migrations/00017.edgeql, packages/generate/src/syntax/toEdgeQL.ts, packages/generate/test/casts.test.ts, packages/generate/test/literals.test.ts, packages/generate/test/operators.test.ts, packages/generate/test/sets.test.ts, packages/generate/test/with.test.ts
=> Fix custom scalar types + reflect explicit number types in generated edgeql

packages/generate/src/syntax/path.ts, packages/generate/test/objectTypes.test.ts
Reported on discord: https://discord.com/channels/841451783728529451/1043328322748297258
=> Fix `["*"]` on scoped object in select

packages/generate/src/edgeql-js/generateObjectTypes.ts, packages/generate/src/syntax/select.ts
Should fix this issue: https://discord.com/channels/841451783728529451/849377751370432573/1044628238384779344
=> Fix `filter_single` with exclusive links + allow `AtMostOne` cardinality

packages/generate/src/cli.ts
=> Default to the 'deno' target when running codegen with deno

packages/driver/src/codecs/datetime.ts, packages/driver/src/datatypes/datetime.ts, packages/driver/test/client.test.ts, packages/driver/test/datetime.test.ts
=> Fix rounding when decoding/encoding microseconds in datetime types

packages/generate/src/syntax/cast.ts, packages/generate/test/casts.test.ts
Related to: https://discord.com/channels/841451783728529451/1070107940176003222/1071129622722383912
=> Allow casting empty sets to object type

compileForDeno.ts, packages/driver/src/adapter.deno.ts, packages/driver/src/adapter.shared.deno.ts, packages/driver/src/globals.deno.ts, packages/driver/test/globals.deno.ts, packages/generate/makeSyntax.ts
Fixes issue with building edgedb-deno on windows. (See https://discord.com/channels/841451783728529451/942868006118232114/1077985342956773446)
=> Update to latest deno std lib

packages/generate/src/interfaces.ts
=> Close connection after generating interfaces

.github/workflows/deno-release.yml, .github/workflows/release.yml, .github/workflows/tests.yml, packages/driver/src/adapter.deno.ts, packages/driver/src/adapter.node.ts, packages/driver/src/adapter.shared.deno.ts, packages/driver/src/adapter.shared.node.ts, packages/driver/src/conUtils.server.ts, packages/driver/src/conUtils.ts, packages/driver/src/retry.ts, packages/driver/test/connection.test.ts
Should fix #550
Depends on #547
=> Only search for project dir if needed + check if `--allow-env` before getting env var in Deno

.github/workflows/tests.yml, packages/driver/src/codecs/array.ts, packages/driver/src/codecs/namedtuple.ts, packages/driver/src/codecs/tuple.ts, packages/driver/test/browser.test.ts, packages/driver/test/client.test.ts, packages/generate/jest.config.js, packages/generate/src/builders.ts, packages/generate/src/edgeql-js.ts, packages/generate/src/edgeql-js/generateRuntimeSpec.ts, packages/generate/src/genutil.ts, packages/generate/src/syntax/__spec__.ts, packages/generate/src/syntax/params.ts, packages/generate/test/collections.test.ts, packages/generate/test/globalSetup.ts, packages/generate/test/globals.test.ts, packages/generate/test/group.test.ts, packages/generate/test/insert.test.ts, packages/generate/test/literals.test.ts, packages/generate/test/params.test.ts, packages/generate/test/setupTeardown.ts
Related: https://github.com/edgedb/edgedb/pull/4489
=> Add support for tuples in query args

packages/driver/src/conUtils.ts, packages/driver/test/connection.test.ts
Updates instance name rules as specified in https://github.com/edgedb/edgedb-python/issues/420
Depends on https://github.com/edgedb/shared-client-testcases/pull/25
=> Update to new instance name rules + update testcases

packages/driver/package.json
=> Release v1.2.1

README.md, packages/driver/package.json, packages/driver/src/fetchConn.ts, packages/driver/src/httpScram.ts, packages/driver/test/browser.test.ts, yarn.lock
=> Remove automatic polyfill of fetch

docs/select.rst
Should be double instead of single.
=> Fix backticks

packages/driver/src/ifaces.ts, packages/driver/src/rawConn.ts
Noticed the loose types in #588 and felt like it was worth being a bit more specific here. I decided to fix a few small linting issues in the imports since I was touching the imports.
=> Better types for ClientHandshakeOptions

packages/driver/src/httpScram.ts
This PR improves error handling in HTTP-SCRAM auth module by rigorously checking that the responses provide all the expected data and exposing the underlying server responses when those checks fail.
=> improve error handling with HTTP-SCRAM auth

docs/queries.rst
Didn't add any reference to these newly exported types in the docs! 🙈
=> Document the types from the queries generator

packages/driver/package.json, packages/generate/package.json
- `edgedb` 1.2.2 -> 1.2.3
- `@edgedb/generate` 0.1.1 -> 0.2.0
=> Release v1.2.3 and @edgedb/generate v0.2.0

packages/driver/src/fetchConn.ts, packages/driver/src/primitives/buffer.ts, packages/driver/src/rawConn.ts
This flag is now a constant `false` as of #638
=> Remove the RingBuffer overflow flag

packages/driver/test/retryConnError.test.ts
This test fails pretty regularly, so in an effort to try to track down which part of this isn't working consistently, I'm breaking it up into it's constituent pieces to hopefully catch the stray failure.
=> Break apart flaky test

packages/generate/src/queries.ts
=> fix(generate): write the generated query file to the source's path

packages/driver/src/reflection/queries/scalars.ts
Closes #569 
This was fixed upstream in https://github.com/edgedb/edgedb/pull/5499
=> Revert temporary fix for ISE in scalar query

README.md
Forgot to update this in the #622 update.
=> Update reference to new queries infix

docs/for.rst
Break down the bulk insert section for easier reading for both people and machines.
=> Add subsections to the e.for bulk insert docs

packages/driver/src/conUtils.ts
=> Add support for project default database

packages/generate/src/cli.ts, packages/generate/src/edgeql-js.ts, packages/generate/src/interfaces.ts
=> Move client close to top level cli file

.github/workflows/tests.yml, docs/generation.rst, docs/index.rst, docs/interfaces.rst, docs/queries.rst, docs/querybuilder.rst
Add translation of `npm` -> `bun` for installation and generator operation.
Closes #761
=> Add bun driver and generator instructions

.github/workflows/release.yml
=> Fix typo in release GitHub action

.github/workflows/release.yml
I went ahead and ran this through some validation this time, so _hopefully_ this is all good now.
=> Fix another small typo in release action

packages/auth-core/src/core.ts, packages/auth-nextjs/src/app/index.ts
https://github.com/edgedb/edgedb/blob/639c91e9207275c114828556a1b00c4a3029d8c1/edb/server/protocol/auth_ext/http.py#L612C9-L612C20
=> Pass `verify_url` in the `resendVerificationEmail` Next.js server action

packages/create/README.md
Related issue: https://github.com/edgedb/edgedb-js/issues/848
=> Add README.md for the @edgedb/create package

packages/driver/src/baseConn.ts
Rather than only the most recent one used.
I've got a few states, and cycling between them causes them to be recalculated on every use.
=> Cache session serialized state for its lifetime

packages/create/src/recipes/nextjs/index.ts
Reasoning: The `use TS` question feels like a `yes / no` question, so it felt a bit weird to have `TypeScript / JavaScript` answers. I changed it to `yes/no` with `yes` as the default.
=> Update create next app question

packages/generate/package.json, yarn.lock
=> Move TOML dependency to direct dependency

integration-tests/legacy/package.json, integration-tests/lts/bench.ts, integration-tests/lts/package.json, integration-tests/nightly/package.json, integration-tests/stable/package.json, package.json, packages/auth-core/package.json, packages/auth-express/package.json, packages/auth-nextjs/package.json, packages/auth-remix/package.json, packages/auth-sveltekit/package.json, packages/create/package.json, packages/driver/package.json, packages/generate/package.json, yarn.lock
Following 5.4.x closely to see if performance gets any better for literals.
=> Bump dev TypeScript to latest 5.4.x

packages/driver/src/cli.mts
Does a better job of perserving a cross-platform path, and updates the self-reference check to skip any Windows scripts which is how the `package.json#bin` option works on Windows rather than a symlink.
Huge thanks to @Sikarii for the help troubleshooting and coming up with the final shape of the solution here.
=> Better Windows support for wrapper

integration-tests/lts/operators.test.ts, packages/generate/src/edgeql-js/generateFunctionTypes.ts, packages/generate/src/syntax/cardinality.ts, packages/generate/src/syntax/funcops.ts
Should correctly generates the cardinality of coalesce(??) operation result.
=> Add coalesceCardinalities type & func

packages/auth-nextjs/src/app/index.ts, packages/auth-nextjs/src/shared.client.ts, packages/auth-nextjs/src/shared.ts
Will follow-up with similar changes to the other frameworks.
=> Set cookies to `Secure` when base URL is `https`

packages/auth-express/package.json, packages/auth-nextjs/package.json, packages/auth-remix/package.json, packages/auth-sveltekit/package.json
- `@edgedb/auth-express` 0.2.0
- `@edgedb/auth-nextjs` 0.3.0
- `@edgedb/auth-remix` 0.2.0
- `@edgedb/auth-sveltekit` 0.2.0
=> Release auth helper libraries

integration-tests/legacy/globalSetup.ts, integration-tests/legacy/smoke.test.ts, integration-tests/lts/bench.ts, integration-tests/lts/casts.test.ts, integration-tests/lts/collections.test.ts, integration-tests/lts/delete.test.ts, integration-tests/lts/for.test.ts, integration-tests/lts/functions.test.ts, integration-tests/lts/globalSetup.ts, integration-tests/lts/globals.test.ts, integration-tests/lts/group.test.ts, integration-tests/lts/insert.test.ts, integration-tests/lts/json.test.ts, integration-tests/lts/literals.test.ts, integration-tests/lts/objectTypes.test.ts, integration-tests/lts/operators.test.ts, integration-tests/lts/params.test.ts, integration-tests/lts/paths.test.ts, integration-tests/lts/pgvector.test.ts, integration-tests/lts/primitives.test.ts, integration-tests/lts/select.test.ts, integration-tests/lts/sets.test.ts, integration-tests/lts/setupTeardown.ts, integration-tests/lts/update.test.ts, integration-tests/lts/with.test.ts, integration-tests/nightly/globalSetup.ts, integration-tests/stable/auth.test.ts, integration-tests/stable/globalSetup.ts, package.json
=> Include integration tests in prettier glob

integration-tests/lts/bench.ts, integration-tests/lts/operators.test.ts
To make it even more clear when we improve after this point.
=> Add more e.op benchmarks

packages/driver/src/conUtils.ts
=> Include `branch` in `explainConfig` output

packages/auth-express/package.json, packages/auth-nextjs/package.json, packages/auth-remix/package.json, packages/auth-sveltekit/package.json
- `@edgedb/auth-express` 0.2.2
- `@edgedb/auth-nextjs` 0.3.2
- `@edgedb/auth-remix` 0.2.2
- `@edgedb/auth-sveltekit` 0.2.2
=> Release @edgedb/auth-*

docs/for.rst
Context: https://x.com/andrewingram/status/1834182412546281694
=> docs: minor code example fix

packages/driver/genErrors.mjs, packages/driver/src/codecs/boolean.ts, packages/driver/src/codecs/bytes.ts, packages/driver/src/codecs/datetime.ts, packages/driver/src/codecs/ifaces.ts, packages/driver/src/codecs/json.ts, packages/driver/src/codecs/memory.ts, packages/driver/src/codecs/numbers.ts, packages/driver/src/codecs/numerics.ts, packages/driver/src/codecs/pgvector.ts, packages/driver/src/codecs/text.ts, packages/driver/src/codecs/uuid.ts, packages/driver/src/datatypes/datetime.ts, packages/driver/src/errors/base.ts, packages/driver/src/errors/index.ts, packages/driver/src/errors/map.ts, packages/driver/src/fetchConn.ts, packages/driver/src/rawConn.ts, packages/driver/src/reflection/strictMap.ts, packages/tsconfig/base.json
This matches the default in Deno 2.0 and makes sense for us to use given
how much we use inheritance.
---
This was failing the driver tests for me locally because I was testing out Deno 2, so figured I'd make this a separate PR to make subsequent PRs for Deno 2 compat a bit smaller.
=> Set noImplicitOveride: true in tsconfig

packages/driver/test/connection-config.test.ts, packages/driver/test/testUtil.ts
I'll add test explanations in the morning.
=> Driver tests with both edgedb and gel env vars

packages/create/src/recipes/_base/index.ts, packages/create/src/recipes/_gel/index.ts, packages/create/src/utils.ts
Use PackageManager class.
Use user's package runner to run the Gel CLI instead of installing it.
=> edgedb-js/create refactor

integration-tests/lts/select.test.ts, packages/generate/src/syntax/toEdgeQL.ts
Fixes #808
When walking the expr tree the scoped copy of a select/update expr passed to the shape should have been treated as an opaque reference and not walked, since it will get walked again by the enclosing select/update.
Currently we are only checking this in path expressions (eg. `movie.title`) and not when the scoped expr appears anywhere else (eg. `movie.is(e.Movie)`). And since the expr is getting walked multiple times, it's messing up the ref counting, and exprs are getting hoisted when they shouldn't, causing the broken queries in #808.
=> Fix querybuilder generated query when using unpathed scoped expr

packages/driver/src/baseClient.ts, packages/driver/src/options.ts, packages/driver/src/transaction.ts, packages/driver/test/client.test.ts
Uncover two bugs in the process:
- SQL codecs were accessed in different places by two different names "_private_sql_row" and "sql_row", so really SQL return configuration only worked once :)
- There was a pathway when options object leaked codecs from one version to another (because we want to make things fast!)
Both bugs are fixed as part of this commit.
=> Implement Transaction.withSQLRowMode() method

.github/workflows/tests.yml
Also fix which tests get run with 6.0
=> Bump to 6.0-rc.2

edgedb/ai/index.ts, packages/ai/README.md, packages/ai/src/core.ts, packages/ai/src/types.ts
Related https://github.com/geldata/gel-python/pull/578
=> Rename GelAI to RAGClient

.github/workflows/tests.yml
=> Update server versions for 6.0 going stable

.github/workflows/release.edgedb.yml, edgedb/ai/package.json, edgedb/auth-core/package.json, edgedb/auth-express/package.json, edgedb/auth-nextjs/package.json, edgedb/auth-remix/package.json, edgedb/auth-sveltekit/package.json, edgedb/create/package.json, edgedb/edgedb/package.json, edgedb/generate/package.json
And bump to next patch version
=> Un-deprecate alias packages

packages/ai/src/core.ts
We changed the response key from `response` to `text` in the AI RAG response in 6.0. This commit checks both the old and new keys and attempts to throw more helpful intermediate errors as well.
Closes #1251
=> Update AI RAG response parsing

packages/ai/README.md
Also remove the half-baked reference section, this will be in the docs.
=> Update `@gel/ai` README for latest API

packages/generate/src/edgeql-js/generateCastMaps.ts
Fixes #1242.
This changes the `scalarCastableFrom`/`scalarAssignableBy` types to just pick the type based on the given type's FQN.
This is much easier for TS, esp with generated enums, as their members are statically written as well and TS was duck checking all of these.
```diff
- export type scalarAssignableBy<T extends $.ScalarType> =
- T extends _std.number ? _std.number :
- T extends _std.int64 ? _std.int64 :
- ...
+ export interface ScalarAssignableByMap {
+   "std::number": _std.$number;
+   "std::int64": _std.$int64;
+   ...
+ }
```
This also changes `getSharedParentScalar` to compare against the types' FQN.
This should be much more performant and still safe since these are scalar types with unique names.
We can also skip enumerating every case if `A` & `B` are the same.
This saves …
=> [QB] Optimize scalar cast maps
